//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.03 at 06:21:26 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.shipping.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for Price complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Price">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RATEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SERVICEDESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OPTIONDESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RATE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="RESULT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Price", propOrder = {
        "rateid",
        "service",
        "servicedesc",
        "option",
        "optiondesc",
        "currency",
        "rate",
        "result"
})
public class Price {

    @XmlElement(name = "RATEID", required = true)
    protected String rateid;
    @XmlElement(name = "SERVICE", required = true)
    protected String service;
    @XmlElement(name = "SERVICEDESC", required = true)
    protected String servicedesc;
    @XmlElement(name = "OPTION", required = true)
    protected String option;
    @XmlElement(name = "OPTIONDESC", required = true)
    protected String optiondesc;
    @XmlElement(name = "CURRENCY", required = true)
    protected String currency;
    @XmlElement(name = "RATE", required = true)
    protected BigDecimal rate;
    @XmlElement(name = "RESULT", required = true)
    protected String result;

    /**
     * Gets the value of the rateid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRATEID() {
        return rateid;
    }

    /**
     * Sets the value of the rateid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRATEID(String value) {
        this.rateid = value;
    }

    /**
     * Gets the value of the service property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSERVICE() {
        return service;
    }

    /**
     * Sets the value of the service property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSERVICE(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the servicedesc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSERVICEDESC() {
        return servicedesc;
    }

    /**
     * Sets the value of the servicedesc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSERVICEDESC(String value) {
        this.servicedesc = value;
    }

    /**
     * Gets the value of the option property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOPTION() {
        return option;
    }

    /**
     * Sets the value of the option property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOPTION(String value) {
        this.option = value;
    }

    /**
     * Gets the value of the optiondesc property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOPTIONDESC() {
        return optiondesc;
    }

    /**
     * Sets the value of the optiondesc property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOPTIONDESC(String value) {
        this.optiondesc = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCURRENCY(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the rate property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getRATE() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setRATE(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the result property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRESULT(String value) {
        this.result = value;
    }

}
