//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 09:59:03 AM ICT 
//


package com.gms.delivery.tnt.xmlpi.label.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for measurementsType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="measurementsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="length" type="{}doubleMaxExclusive100MinInclusive0.01"/>
 *         &lt;element name="width" type="{}doubleMaxExclusive100MinInclusive0.01"/>
 *         &lt;element name="height" type="{}doubleMaxExclusive100MinInclusive0.01"/>
 *         &lt;element name="weight" type="{}doubleMaxExclusive100000MinInclusive0.01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "measurementsType", propOrder = {
        "length",
        "width",
        "height",
        "weight"
})
public class MeasurementsType {

    protected double length;
    protected double width;
    protected double height;
    protected double weight;

    /**
     * Gets the value of the length property.
     */
    public double getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     */
    public void setLength(double value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     */
    public double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(double value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the weight property.
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     */
    public void setWeight(double value) {
        this.weight = value;
    }

}
