-- update customer summary temp table using for the customer summary report
DROP TABLE IF EXISTS tmp_xms_tbl_customer_summary;
create table tmp_xms_tbl_customer_summary
(
	rpt_txn_id varchar(128),
	customer_code bigint(20), 
	customer_name varchar(500), 
	sale_rep_name varchar(200), 
	-- Total
	cust_cost decimal(20,2), 
	cust_tax decimal(20,2), 
	fran_cost decimal(20,2), 
	fran_tax decimal(20,2), 
	carrier_cost decimal(20,2), 
	carrier_tax decimal(20,2), 
	shipment_count bigint(20),
	-- Base charge
	cust_base_charge_cost decimal(20,2),
	cust_base_charge_tax decimal(20,2),
	fran_base_charge_cost decimal(20,2),
	fran_base_charge_tax decimal(20,2),
	carrier_base_charge_cost decimal(20,2),
	carrier_base_charge_tax decimal(20,2),
	-- Surcharge tax
	cust_surcharge_cost decimal(20,2), 
	cust_surcharge_tax decimal(20,2), 
	fran_surcharge_cost decimal(20,2), 
	fran_surcharge_tax decimal(20,2), 
	carrier_surcharge_cost decimal(20,2), 
	carrier_surcharge_tax decimal(20,2), 
	-- DHL
	dhl_cust_cost decimal(20,2), 
	dhl_cust_tax decimal(20,2), 
	dhl_fran_cost decimal(20,2), 
	dhl_fran_tax decimal(20,2), 
	dhl_carrier_cost decimal(20,2), 
	dhl_carrier_tax decimal(20,2), 
	dhl_shipment_count bigint(20),
	-- DHL Surcharge tax
	dhl_cust_surcharge_cost decimal(20,2), 
	dhl_cust_surcharge_tax decimal(20,2), 
	dhl_fran_surcharge_cost decimal(20,2), 
	dhl_fran_surcharge_tax decimal(20,2), 
	dhl_carrier_surcharge_cost decimal(20,2), 
	dhl_carrier_surcharge_tax decimal(20,2), 
	-- DHL Domestic
	dhl_dom_cust_cost decimal(20,2), 
	dhl_dom_cust_tax decimal(20,2), 
	dhl_dom_fran_cost decimal(20,2), 
	dhl_dom_fran_tax decimal(20,2), 
	dhl_dom_carrier_cost decimal(20,2), 
	dhl_dom_carrier_tax decimal(20,2), 
	dhl_dom_shipment_count bigint(20),
	-- DHL Domestic Surcharge tax
	dhl_dom_cust_surcharge_cost decimal(20,2), 
	dhl_dom_cust_surcharge_tax decimal(20,2), 
	dhl_dom_fran_surcharge_cost decimal(20,2), 
	dhl_dom_fran_surcharge_tax decimal(20,2), 
	dhl_dom_carrier_surcharge_cost decimal(20,2), 
	dhl_dom_carrier_surcharge_tax decimal(20,2), 
	-- TNT Domestic
	tnt_dom_cust_cost decimal(20,2), 
	tnt_dom_cust_tax decimal(20,2), 
	tnt_dom_fran_cost decimal(20,2), 
	tnt_dom_fran_tax decimal(20,2), 
	tnt_dom_carrier_cost decimal(20,2), 
	tnt_dom_carrier_tax decimal(20,2), 
	tnt_dom_shipment_count bigint(20),
	-- TNT Domestic Surcharge tax
	tnt_dom_cust_surcharge_cost decimal(20,2), 
	tnt_dom_cust_surcharge_tax decimal(20,2), 
	tnt_dom_fran_surcharge_cost decimal(20,2), 
	tnt_dom_fran_surcharge_tax decimal(20,2), 
	tnt_dom_carrier_surcharge_cost decimal(20,2), 
	tnt_dom_carrier_surcharge_tax decimal(20,2), 
	-- Toll Priority
	toll_priority_cust_cost decimal(20,2), 
	toll_priority_cust_tax decimal(20,2), 
	toll_priority_fran_cost decimal(20,2), 
	toll_priority_fran_tax decimal(20,2), 
	toll_priority_carrier_cost decimal(20,2), 
	toll_priority_carrier_tax decimal(20,2), 
	toll_priority_shipment_count bigint(20),
	-- Toll Priority Surcharge tax
	toll_priority_cust_surcharge_cost decimal(20,2), 
	toll_priority_cust_surcharge_tax decimal(20,2), 
	toll_priority_fran_surcharge_cost decimal(20,2), 
	toll_priority_fran_surcharge_tax decimal(20,2), 
	toll_priority_carrier_surcharge_cost decimal(20,2), 
	toll_priority_carrier_surcharge_tax decimal(20,2), 
	-- Other
	other_cust_cost decimal(20,2), 
	other_cust_tax decimal(20,2), 
	other_fran_cost decimal(20,2), 
	other_fran_tax decimal(20,2), 
	other_carrier_cost decimal(20,2), 
	other_carrier_tax decimal(20,2), 
	other_shipment_count bigint(20),
	-- Other Surcharge tax
	other_cust_surcharge_cost decimal(20,2), 
	other_cust_surcharge_tax decimal(20,2), 
	other_fran_surcharge_cost decimal(20,2), 
	other_fran_surcharge_tax decimal(20,2), 
	other_carrier_surcharge_cost decimal(20,2), 
	other_carrier_surcharge_tax decimal(20,2), 
    index rpt_txn_id(rpt_txn_id)
);