//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 05:26:43 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.tracking.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="Consignment" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ConsignmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="AlternativeConsignmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="OriginDepot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="OriginDepotName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="CustomerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="CollectionDate" type="{}DateType" minOccurs="0"/>
 *                     &lt;element name="DeliveryTown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="DeliveryDate" type="{}DateType" minOccurs="0"/>
 *                     &lt;element name="DeliveryTime" type="{}TimeType" minOccurs="0"/>
 *                     &lt;element name="Signatory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="SummaryCode">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="EXC"/>
 *                           &lt;enumeration value="INT"/>
 *                           &lt;enumeration value="DEL"/>
 *                           &lt;enumeration value="CNF"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="DestinationCountry" type="{}CountryStructure" minOccurs="0"/>
 *                     &lt;element name="OriginCountry" type="{}CountryStructure" minOccurs="0"/>
 *                     &lt;element name="TermsOfPaymentAccount" type="{}AccountStructure" minOccurs="0"/>
 *                     &lt;element name="SenderAccount" type="{}AccountStructure" minOccurs="0"/>
 *                     &lt;element name="PieceQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                     &lt;element name="StatusData" type="{}StatusStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="PackageSummary" type="{}PackageSummaryStructure" minOccurs="0"/>
 *                     &lt;element name="ShipmentSummary" type="{}ShipmentSummaryStructure" minOccurs="0"/>
 *                     &lt;element name="Addresses" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Address" type="{}AddressStructure" maxOccurs="4"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="POD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="access" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="public"/>
 *                         &lt;enumeration value="full"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ContinuationKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="Error" type="{}ErrorStructure"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "consignment",
        "continuationKey",
        "error"
})
@XmlRootElement(name = "TrackResponse")
public class TrackResponse {

    @XmlElement(name = "Consignment")
    protected List<TrackResponse.Consignment> consignment;
    @XmlElement(name = "ContinuationKey")
    protected String continuationKey;
    @XmlElement(name = "Error")
    protected ErrorStructure error;

    /**
     * Gets the value of the consignment property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consignment property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsignment().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrackResponse.Consignment }
     */
    public List<TrackResponse.Consignment> getConsignment() {
        if (consignment == null) {
            consignment = new ArrayList<TrackResponse.Consignment>();
        }
        return this.consignment;
    }

    /**
     * Gets the value of the continuationKey property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContinuationKey() {
        return continuationKey;
    }

    /**
     * Sets the value of the continuationKey property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContinuationKey(String value) {
        this.continuationKey = value;
    }

    /**
     * Gets the value of the error property.
     *
     * @return possible object is
     * {@link ErrorStructure }
     */
    public ErrorStructure getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     *
     * @param value allowed object is
     *              {@link ErrorStructure }
     */
    public void setError(ErrorStructure value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ConsignmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AlternativeConsignmentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OriginDepot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OriginDepotName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CustomerReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CollectionDate" type="{}DateType" minOccurs="0"/>
     *         &lt;element name="DeliveryTown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DeliveryDate" type="{}DateType" minOccurs="0"/>
     *         &lt;element name="DeliveryTime" type="{}TimeType" minOccurs="0"/>
     *         &lt;element name="Signatory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="SummaryCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="EXC"/>
     *               &lt;enumeration value="INT"/>
     *               &lt;enumeration value="DEL"/>
     *               &lt;enumeration value="CNF"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DestinationCountry" type="{}CountryStructure" minOccurs="0"/>
     *         &lt;element name="OriginCountry" type="{}CountryStructure" minOccurs="0"/>
     *         &lt;element name="TermsOfPaymentAccount" type="{}AccountStructure" minOccurs="0"/>
     *         &lt;element name="SenderAccount" type="{}AccountStructure" minOccurs="0"/>
     *         &lt;element name="PieceQuantity" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="StatusData" type="{}StatusStructure" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="PackageSummary" type="{}PackageSummaryStructure" minOccurs="0"/>
     *         &lt;element name="ShipmentSummary" type="{}ShipmentSummaryStructure" minOccurs="0"/>
     *         &lt;element name="Addresses" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Address" type="{}AddressStructure" maxOccurs="4"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="POD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="access" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="public"/>
     *             &lt;enumeration value="full"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "consignmentNumber",
            "alternativeConsignmentNumber",
            "originDepot",
            "originDepotName",
            "customerReference",
            "collectionDate",
            "deliveryTown",
            "deliveryDate",
            "deliveryTime",
            "signatory",
            "summaryCode",
            "destinationCountry",
            "originCountry",
            "termsOfPaymentAccount",
            "senderAccount",
            "pieceQuantity",
            "statusData",
            "packageSummary",
            "shipmentSummary",
            "addresses",
            "pod"
    })
    public static class Consignment {

        @XmlElement(name = "ConsignmentNumber")
        protected String consignmentNumber;
        @XmlElement(name = "AlternativeConsignmentNumber")
        protected String alternativeConsignmentNumber;
        @XmlElement(name = "OriginDepot")
        protected String originDepot;
        @XmlElement(name = "OriginDepotName")
        protected String originDepotName;
        @XmlElement(name = "CustomerReference")
        protected String customerReference;
        @XmlElement(name = "CollectionDate")
        protected DateType collectionDate;
        @XmlElement(name = "DeliveryTown")
        protected String deliveryTown;
        @XmlElement(name = "DeliveryDate")
        protected DateType deliveryDate;
        @XmlElement(name = "DeliveryTime")
        protected TimeType deliveryTime;
        @XmlElement(name = "Signatory")
        protected String signatory;
        @XmlElement(name = "SummaryCode", required = true)
        protected String summaryCode;
        @XmlElement(name = "DestinationCountry")
        protected CountryStructure destinationCountry;
        @XmlElement(name = "OriginCountry")
        protected CountryStructure originCountry;
        @XmlElement(name = "TermsOfPaymentAccount")
        protected AccountStructure termsOfPaymentAccount;
        @XmlElement(name = "SenderAccount")
        protected AccountStructure senderAccount;
        @XmlElement(name = "PieceQuantity")
        protected Object pieceQuantity;
        @XmlElement(name = "StatusData")
        protected List<StatusStructure> statusData;
        @XmlElement(name = "PackageSummary")
        protected PackageSummaryStructure packageSummary;
        @XmlElement(name = "ShipmentSummary")
        protected ShipmentSummaryStructure shipmentSummary;
        @XmlElement(name = "Addresses")
        protected TrackResponse.Consignment.Addresses addresses;
        @XmlElement(name = "POD")
        protected String pod;
        @XmlAttribute(name = "access", required = true)
        protected String access;

        /**
         * Gets the value of the consignmentNumber property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getConsignmentNumber() {
            return consignmentNumber;
        }

        /**
         * Sets the value of the consignmentNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setConsignmentNumber(String value) {
            this.consignmentNumber = value;
        }

        /**
         * Gets the value of the alternativeConsignmentNumber property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getAlternativeConsignmentNumber() {
            return alternativeConsignmentNumber;
        }

        /**
         * Sets the value of the alternativeConsignmentNumber property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAlternativeConsignmentNumber(String value) {
            this.alternativeConsignmentNumber = value;
        }

        /**
         * Gets the value of the originDepot property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOriginDepot() {
            return originDepot;
        }

        /**
         * Sets the value of the originDepot property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOriginDepot(String value) {
            this.originDepot = value;
        }

        /**
         * Gets the value of the originDepotName property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOriginDepotName() {
            return originDepotName;
        }

        /**
         * Sets the value of the originDepotName property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOriginDepotName(String value) {
            this.originDepotName = value;
        }

        /**
         * Gets the value of the customerReference property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCustomerReference() {
            return customerReference;
        }

        /**
         * Sets the value of the customerReference property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCustomerReference(String value) {
            this.customerReference = value;
        }

        /**
         * Gets the value of the collectionDate property.
         *
         * @return possible object is
         * {@link DateType }
         */
        public DateType getCollectionDate() {
            return collectionDate;
        }

        /**
         * Sets the value of the collectionDate property.
         *
         * @param value allowed object is
         *              {@link DateType }
         */
        public void setCollectionDate(DateType value) {
            this.collectionDate = value;
        }

        /**
         * Gets the value of the deliveryTown property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getDeliveryTown() {
            return deliveryTown;
        }

        /**
         * Sets the value of the deliveryTown property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setDeliveryTown(String value) {
            this.deliveryTown = value;
        }

        /**
         * Gets the value of the deliveryDate property.
         *
         * @return possible object is
         * {@link DateType }
         */
        public DateType getDeliveryDate() {
            return deliveryDate;
        }

        /**
         * Sets the value of the deliveryDate property.
         *
         * @param value allowed object is
         *              {@link DateType }
         */
        public void setDeliveryDate(DateType value) {
            this.deliveryDate = value;
        }

        /**
         * Gets the value of the deliveryTime property.
         *
         * @return possible object is
         * {@link TimeType }
         */
        public TimeType getDeliveryTime() {
            return deliveryTime;
        }

        /**
         * Sets the value of the deliveryTime property.
         *
         * @param value allowed object is
         *              {@link TimeType }
         */
        public void setDeliveryTime(TimeType value) {
            this.deliveryTime = value;
        }

        /**
         * Gets the value of the signatory property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSignatory() {
            return signatory;
        }

        /**
         * Sets the value of the signatory property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSignatory(String value) {
            this.signatory = value;
        }

        /**
         * Gets the value of the summaryCode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getSummaryCode() {
            return summaryCode;
        }

        /**
         * Sets the value of the summaryCode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSummaryCode(String value) {
            this.summaryCode = value;
        }

        /**
         * Gets the value of the destinationCountry property.
         *
         * @return possible object is
         * {@link CountryStructure }
         */
        public CountryStructure getDestinationCountry() {
            return destinationCountry;
        }

        /**
         * Sets the value of the destinationCountry property.
         *
         * @param value allowed object is
         *              {@link CountryStructure }
         */
        public void setDestinationCountry(CountryStructure value) {
            this.destinationCountry = value;
        }

        /**
         * Gets the value of the originCountry property.
         *
         * @return possible object is
         * {@link CountryStructure }
         */
        public CountryStructure getOriginCountry() {
            return originCountry;
        }

        /**
         * Sets the value of the originCountry property.
         *
         * @param value allowed object is
         *              {@link CountryStructure }
         */
        public void setOriginCountry(CountryStructure value) {
            this.originCountry = value;
        }

        /**
         * Gets the value of the termsOfPaymentAccount property.
         *
         * @return possible object is
         * {@link AccountStructure }
         */
        public AccountStructure getTermsOfPaymentAccount() {
            return termsOfPaymentAccount;
        }

        /**
         * Sets the value of the termsOfPaymentAccount property.
         *
         * @param value allowed object is
         *              {@link AccountStructure }
         */
        public void setTermsOfPaymentAccount(AccountStructure value) {
            this.termsOfPaymentAccount = value;
        }

        /**
         * Gets the value of the senderAccount property.
         *
         * @return possible object is
         * {@link AccountStructure }
         */
        public AccountStructure getSenderAccount() {
            return senderAccount;
        }

        /**
         * Sets the value of the senderAccount property.
         *
         * @param value allowed object is
         *              {@link AccountStructure }
         */
        public void setSenderAccount(AccountStructure value) {
            this.senderAccount = value;
        }

        /**
         * Gets the value of the pieceQuantity property.
         *
         * @return possible object is
         * {@link Object }
         */
        public Object getPieceQuantity() {
            return pieceQuantity;
        }

        /**
         * Sets the value of the pieceQuantity property.
         *
         * @param value allowed object is
         *              {@link Object }
         */
        public void setPieceQuantity(Object value) {
            this.pieceQuantity = value;
        }

        /**
         * Gets the value of the statusData property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the statusData property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStatusData().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StatusStructure }
         */
        public List<StatusStructure> getStatusData() {
            if (statusData == null) {
                statusData = new ArrayList<StatusStructure>();
            }
            return this.statusData;
        }

        /**
         * Gets the value of the packageSummary property.
         *
         * @return possible object is
         * {@link PackageSummaryStructure }
         */
        public PackageSummaryStructure getPackageSummary() {
            return packageSummary;
        }

        /**
         * Sets the value of the packageSummary property.
         *
         * @param value allowed object is
         *              {@link PackageSummaryStructure }
         */
        public void setPackageSummary(PackageSummaryStructure value) {
            this.packageSummary = value;
        }

        /**
         * Gets the value of the shipmentSummary property.
         *
         * @return possible object is
         * {@link ShipmentSummaryStructure }
         */
        public ShipmentSummaryStructure getShipmentSummary() {
            return shipmentSummary;
        }

        /**
         * Sets the value of the shipmentSummary property.
         *
         * @param value allowed object is
         *              {@link ShipmentSummaryStructure }
         */
        public void setShipmentSummary(ShipmentSummaryStructure value) {
            this.shipmentSummary = value;
        }

        /**
         * Gets the value of the addresses property.
         *
         * @return possible object is
         * {@link TrackResponse.Consignment.Addresses }
         */
        public TrackResponse.Consignment.Addresses getAddresses() {
            return addresses;
        }

        /**
         * Sets the value of the addresses property.
         *
         * @param value allowed object is
         *              {@link TrackResponse.Consignment.Addresses }
         */
        public void setAddresses(TrackResponse.Consignment.Addresses value) {
            this.addresses = value;
        }

        /**
         * Gets the value of the pod property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getPOD() {
            return pod;
        }

        /**
         * Sets the value of the pod property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setPOD(String value) {
            this.pod = value;
        }

        /**
         * Gets the value of the access property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getAccess() {
            return access;
        }

        /**
         * Sets the value of the access property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAccess(String value) {
            this.access = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Address" type="{}AddressStructure" maxOccurs="4"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "address"
        })
        public static class Addresses {

            @XmlElement(name = "Address", required = true)
            protected List<AddressStructure> address;

            /**
             * Gets the value of the address property.
             * <p>
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the address property.
             * <p>
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAddress().add(newItem);
             * </pre>
             * <p>
             * <p>
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AddressStructure }
             */
            public List<AddressStructure> getAddress() {
                if (address == null) {
                    address = new ArrayList<AddressStructure>();
                }
                return this.address;
            }

        }

    }

}
