//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 02:49:39 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype.capability.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for DCTDutiable complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DCTDutiable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeclaredCurrency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeclaredValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}float">
 *               &lt;minInclusive value="0.000"/>
 *               &lt;maxInclusive value="999999999999999999.999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCTDutiable", namespace = "http://www.dhl.com/DCTRequestdatatypes", propOrder = {
        "declaredCurrency",
        "declaredValue"
})
public class DCTDutiable {

    @XmlElement(name = "DeclaredCurrency")
    protected String declaredCurrency;
    @XmlElement(name = "DeclaredValue")
    protected BigDecimal declaredValue;

    /**
     * Gets the value of the declaredCurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeclaredCurrency() {
        return declaredCurrency;
    }

    /**
     * Sets the value of the declaredCurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeclaredCurrency(String value) {
        this.declaredCurrency = value;
    }

    /**
     * Gets the value of the declaredValue property.
     *
     * @return possible object is
     * {@link Float }
     */
    public BigDecimal getDeclaredValue() {
        return declaredValue;
    }

    /**
     * Sets the value of the declaredValue property.
     *
     * @param value allowed object is
     *              {@link Float }
     */
    public void setDeclaredValue(BigDecimal value) {
        this.declaredValue = value;
    }

}
