//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 02:49:39 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype.capability.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.gms.delivery.dhl.xmlpi.datatype.capability.request package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DCTRequestDataTypes_QNAME = new QName("http://www.dhl.com/DCTRequestdatatypes", "DCTRequestDataTypes");
    private final static QName _DataTypes_QNAME = new QName("http://www.dhl.com/datatypes", "DataTypes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gms.delivery.dhl.xmlpi.datatype.capability.request
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DCTRequest }
     */
    public DCTRequest createDCTRequest() {
        return new DCTRequest();
    }

    /**
     * Create an instance of {@link BkgDetailsType }
     */
    public BkgDetailsType createBkgDetailsType() {
        return new BkgDetailsType();
    }

    /**
     * Create an instance of {@link ExportLineItem }
     */
    public ExportLineItem createExportLineItem() {
        return new ExportLineItem();
    }

    /**
     * Create an instance of {@link DCTRequest.GetQuote }
     */
    public DCTRequest.GetQuote createDCTRequestGetQuote() {
        return new DCTRequest.GetQuote();
    }

    /**
     * Create an instance of {@link DCTRequest.GetCapability }
     */
    public DCTRequest.GetCapability createDCTRequestGetCapability() {
        return new DCTRequest.GetCapability();
    }

    /**
     * Create an instance of {@link Condition }
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link Commodity }
     */
    public Commodity createCommodity() {
        return new Commodity();
    }

    /**
     * Create an instance of {@link DocImages }
     */
    public DocImages createDocImages() {
        return new DocImages();
    }

    /**
     * Create an instance of {@link PieceDetails }
     */
    public PieceDetails createPieceDetails() {
        return new PieceDetails();
    }

    /**
     * Create an instance of {@link ShipmentDate }
     */
    public ShipmentDate createShipmentDate() {
        return new ShipmentDate();
    }

    /**
     * Create an instance of {@link Consignee }
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link QtdSInAdCur }
     */
    public QtdSInAdCur createQtdSInAdCur() {
        return new QtdSInAdCur();
    }

    /**
     * Create an instance of {@link Email }
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link DocImage }
     */
    public DocImage createDocImage() {
        return new DocImage();
    }

    /**
     * Create an instance of {@link DestinationServiceArea }
     */
    public DestinationServiceArea createDestinationServiceArea() {
        return new DestinationServiceArea();
    }

    /**
     * Create an instance of {@link EventRemarks }
     */
    public EventRemarks createEventRemarks() {
        return new EventRemarks();
    }

    /**
     * Create an instance of {@link Request }
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link WeightSeg }
     */
    public WeightSeg createWeightSeg() {
        return new WeightSeg();
    }

    /**
     * Create an instance of {@link AWBInfo }
     */
    public AWBInfo createAWBInfo() {
        return new AWBInfo();
    }

    /**
     * Create an instance of {@link OriginServiceArea }
     */
    public OriginServiceArea createOriginServiceArea() {
        return new OriginServiceArea();
    }

    /**
     * Create an instance of {@link ShipValResponsePieces }
     */
    public ShipValResponsePieces createShipValResponsePieces() {
        return new ShipValResponsePieces();
    }

    /**
     * Create an instance of {@link Place }
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Response }
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Note }
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Shipment }
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link Label }
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Fault }
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link PieceEvent }
     */
    public PieceEvent createPieceEvent() {
        return new PieceEvent();
    }

    /**
     * Create an instance of {@link BarCodes }
     */
    public BarCodes createBarCodes() {
        return new BarCodes();
    }

    /**
     * Create an instance of {@link com.gms.delivery.dhl.xmlpi.datatype.capability.request.Pieces }
     */
    public com.gms.delivery.dhl.xmlpi.datatype.capability.request.Pieces createPieces() {
        return new com.gms.delivery.dhl.xmlpi.datatype.capability.request.Pieces();
    }

    /**
     * Create an instance of {@link ExportDeclaration }
     */
    public ExportDeclaration createExportDeclaration() {
        return new ExportDeclaration();
    }

    /**
     * Create an instance of {@link Shipper }
     */
    public Shipper createShipper() {
        return new Shipper();
    }

    /**
     * Create an instance of {@link Piece }
     */
    public Piece createPiece() {
        return new Piece();
    }

    /**
     * Create an instance of {@link ShipValResponsePiece }
     */
    public ShipValResponsePiece createShipValResponsePiece() {
        return new ShipValResponsePiece();
    }

    /**
     * Create an instance of {@link PieceFault }
     */
    public PieceFault createPieceFault() {
        return new PieceFault();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link ShipmentEvent }
     */
    public ShipmentEvent createShipmentEvent() {
        return new ShipmentEvent();
    }

    /**
     * Create an instance of {@link TrackingPieces }
     */
    public TrackingPieces createTrackingPieces() {
        return new TrackingPieces();
    }

    /**
     * Create an instance of {@link ServiceHeader }
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link CustomerLogo }
     */
    public CustomerLogo createCustomerLogo() {
        return new CustomerLogo();
    }

    /**
     * Create an instance of {@link Reference }
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link ShipmentDetails }
     */
    public ShipmentDetails createShipmentDetails() {
        return new ShipmentDetails();
    }

    /**
     * Create an instance of {@link PieceInfo }
     */
    public PieceInfo createPieceInfo() {
        return new PieceInfo();
    }

    /**
     * Create an instance of {@link Customer }
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link SpecialService }
     */
    public SpecialService createSpecialService() {
        return new SpecialService();
    }

    /**
     * Create an instance of {@link Billing }
     */
    public Billing createBilling() {
        return new Billing();
    }

    /**
     * Create an instance of {@link Contact }
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link LabelImage }
     */
    public LabelImage createLabelImage() {
        return new LabelImage();
    }

    /**
     * Create an instance of {@link Status }
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link ServiceEvent }
     */
    public ServiceEvent createServiceEvent() {
        return new ServiceEvent();
    }

    /**
     * Create an instance of {@link Dutiable }
     */
    public Dutiable createDutiable() {
        return new Dutiable();
    }

    /**
     * Create an instance of {@link ShipmentInfo }
     */
    public ShipmentInfo createShipmentInfo() {
        return new ShipmentInfo();
    }

    /**
     * Create an instance of {@link ChargeCard }
     */
    public ChargeCard createChargeCard() {
        return new ChargeCard();
    }

    /**
     * Create an instance of {@link ServiceArea }
     */
    public ServiceArea createServiceArea() {
        return new ServiceArea();
    }

    /**
     * Create an instance of {@link QtdShpType }
     */
    public QtdShpType createQtdShpType() {
        return new QtdShpType();
    }

    /**
     * Create an instance of {@link PieceType }
     */
    public PieceType createPieceType() {
        return new PieceType();
    }

    /**
     * Create an instance of {@link DCTDutiable }
     */
    public DCTDutiable createDCTDutiable() {
        return new DCTDutiable();
    }

    /**
     * Create an instance of {@link DCTTo }
     */
    public DCTTo createDCTTo() {
        return new DCTTo();
    }

    /**
     * Create an instance of {@link DCTFrom }
     */
    public DCTFrom createDCTFrom() {
        return new DCTFrom();
    }

    /**
     * Create an instance of {@link QtdShpExChrgType }
     */
    public QtdShpExChrgType createQtdShpExChrgType() {
        return new QtdShpExChrgType();
    }

    /**
     * Create an instance of {@link BkgDetailsType.Pieces }
     */
    public BkgDetailsType.Pieces createBkgDetailsTypePieces() {
        return new BkgDetailsType.Pieces();
    }

    /**
     * Create an instance of {@link ExportLineItem.Weight }
     */
    public ExportLineItem.Weight createExportLineItemWeight() {
        return new ExportLineItem.Weight();
    }

    /**
     * Create an instance of {@link ExportLineItem.License }
     */
    public ExportLineItem.License createExportLineItemLicense() {
        return new ExportLineItem.License();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.dhl.com/DCTRequestdatatypes", name = "DCTRequestDataTypes")
    public JAXBElement<Object> createDCTRequestDataTypes(Object value) {
        return new JAXBElement<Object>(_DCTRequestDataTypes_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.dhl.com/datatypes", name = "DataTypes")
    public JAXBElement<Object> createDataTypes(Object value) {
        return new JAXBElement<Object>(_DataTypes_QNAME, Object.class, null, value);
    }

}
