//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:55:03 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dhl.com/datatypes_global") package com.gms.delivery.dhl.xmlpi.datatype.pickup.response;
