//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:55:03 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype.pickup.response;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceiptTemplate.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReceiptTemplate">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="30"/>
 *     &lt;enumeration value="SHIP_RECPT_A4_RU_PDF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "ReceiptTemplate")
@XmlEnum
public enum ReceiptTemplate {

    @XmlEnumValue("SHIP_RECPT_A4_RU_PDF")
    SHIP_RECPT_A_4_RU_PDF("SHIP_RECPT_A4_RU_PDF");
    private final String value;

    ReceiptTemplate(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReceiptTemplate fromValue(String v) {
        for (ReceiptTemplate c : ReceiptTemplate.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
