//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 03:26:24 PM ICT 
//


package com.gms.delivery.startrack.xmlpi.booking;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for AaEConnoteType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="AaEConnoteType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ATL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ATLNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Account" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ArticleList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Articles" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="BookInDeliverFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BookInNotAfter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BookInNotBefore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ConId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Connotenum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatorName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CreatorPhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CubicVolume" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="CubicWeight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DGClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DGDeadWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DGNumOuterPack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DGTechShipName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DGTradeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DGTypeOuterPack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeadWeight" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DeliverOnDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryLines" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DespatchID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmailLabels" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EmailNotifyFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FromPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FromZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="InvoiceList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="LithiumBatteries" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManifestDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManifestNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PackingGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ParcelProtection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverAddress3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverContactName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverMob" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReceiverPostcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverSuburb" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverTel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ref1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ref2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsCCEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsLabelPrintFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsReceiverEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsSenderContact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsSenderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsSenderTel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnsServiceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderAddress3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderCompany" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderFax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderPostcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderSuburb" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderTel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ServiceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ServiceLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ServiceRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SmsNotifyFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SoftwareType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StarTrackAcct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Sticker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubRisk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThermalLabelPDF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UNNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UnitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Zone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AaEConnoteType", propOrder = {
        "atl",
        "atlNum",
        "account",
        "articleList",
        "articles",
        "bookInDeliverFlag",
        "bookInNotAfter",
        "bookInNotBefore",
        "cid",
        "conId",
        "connotenum",
        "creatorName",
        "creatorPhone",
        "cubicVolume",
        "cubicWeight",
        "dgClass",
        "dgDeadWeight",
        "dgNumOuterPack",
        "dgTechShipName",
        "dgTradeName",
        "dgTypeOuterPack",
        "deadWeight",
        "deliverOnDate",
        "deliveryLines",
        "deliveryWindow",
        "description",
        "despatchID",
        "emailAddress",
        "emailLabels",
        "emailNotifyFlag",
        "fromPort",
        "fromZone",
        "height",
        "invoiceList",
        "length",
        "lithiumBatteries",
        "manifestDate",
        "manifestNumber",
        "packingGroup",
        "parcelProtection",
        "port",
        "productCode",
        "receiverAddress1",
        "receiverAddress2",
        "receiverAddress3",
        "receiverCompanyName",
        "receiverContactName",
        "receiverEmail",
        "receiverFax",
        "receiverMob",
        "receiverPostcode",
        "receiverSuburb",
        "receiverTel",
        "ref1",
        "ref2",
        "returnsCCEmail",
        "returnsLabelPrintFlag",
        "returnsReceiverEmail",
        "returnsSenderContact",
        "returnsSenderEmail",
        "returnsSenderTel",
        "returnsServiceType",
        "senderAddress1",
        "senderAddress2",
        "senderAddress3",
        "senderCompany",
        "senderEmail",
        "senderFax",
        "senderMobile",
        "senderPostcode",
        "senderSuburb",
        "senderTel",
        "serviceCode",
        "serviceLabel",
        "serviceRef",
        "smsNotifyFlag",
        "softwareType",
        "starTrackAcct",
        "sticker",
        "subRisk",
        "thermalLabelPDF",
        "unNumber",
        "unitType",
        "width",
        "zone"
})
public class AaEConnoteType {

    @XmlElement(name = "ATL", required = true, nillable = true)
    protected String atl;
    @XmlElementRef(name = "ATLNum", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> atlNum;
    @XmlElement(name = "Account", required = true, nillable = true)
    protected String account;
    @XmlElementRef(name = "ArticleList", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> articleList;
    @XmlElement(name = "Articles")
    protected int articles;
    @XmlElementRef(name = "BookInDeliverFlag", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bookInDeliverFlag;
    @XmlElementRef(name = "BookInNotAfter", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bookInNotAfter;
    @XmlElementRef(name = "BookInNotBefore", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bookInNotBefore;
    @XmlElement(name = "CID", required = true, nillable = true)
    protected String cid;
    @XmlElement(name = "ConId")
    protected Integer conId;
    @XmlElementRef(name = "Connotenum", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> connotenum;
    @XmlElement(name = "CreatorName", required = true, nillable = true)
    protected String creatorName;
    @XmlElement(name = "CreatorPhone", required = true, nillable = true)
    protected String creatorPhone;
    @XmlElement(name = "CubicVolume")
    protected Integer cubicVolume;
    @XmlElement(name = "CubicWeight", required = true, nillable = true)
    protected String cubicWeight;
    @XmlElementRef(name = "DGClass", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgClass;
    @XmlElementRef(name = "DGDeadWeight", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgDeadWeight;
    @XmlElementRef(name = "DGNumOuterPack", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgNumOuterPack;
    @XmlElementRef(name = "DGTechShipName", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgTechShipName;
    @XmlElementRef(name = "DGTradeName", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgTradeName;
    @XmlElementRef(name = "DGTypeOuterPack", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> dgTypeOuterPack;
    @XmlElement(name = "DeadWeight", required = true, nillable = true)
    protected String deadWeight;
    @XmlElementRef(name = "DeliverOnDate", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deliverOnDate;
    @XmlElementRef(name = "DeliveryLines", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deliveryLines;
    @XmlElementRef(name = "DeliveryWindow", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> deliveryWindow;
    @XmlElement(name = "Description", required = true, nillable = true)
    protected String description;
    @XmlElementRef(name = "DespatchID", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> despatchID;
    @XmlElementRef(name = "EmailAddress", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> emailAddress;
    @XmlElement(name = "EmailLabels", required = true, nillable = true)
    protected String emailLabels;
    @XmlElementRef(name = "EmailNotifyFlag", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> emailNotifyFlag;
    @XmlElementRef(name = "FromPort", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fromPort;
    @XmlElementRef(name = "FromZone", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fromZone;
    @XmlElement(name = "Height")
    protected int height;
    @XmlElementRef(name = "InvoiceList", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> invoiceList;
    @XmlElement(name = "Length")
    protected int length;
    @XmlElementRef(name = "LithiumBatteries", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lithiumBatteries;
    @XmlElementRef(name = "ManifestDate", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> manifestDate;
    @XmlElementRef(name = "ManifestNumber", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> manifestNumber;
    @XmlElementRef(name = "PackingGroup", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> packingGroup;
    @XmlElementRef(name = "ParcelProtection", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> parcelProtection;
    @XmlElementRef(name = "Port", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> port;
    @XmlElementRef(name = "ProductCode", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> productCode;
    @XmlElement(name = "ReceiverAddress1", required = true, nillable = true)
    protected String receiverAddress1;
    @XmlElementRef(name = "ReceiverAddress2", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverAddress2;
    @XmlElementRef(name = "ReceiverAddress3", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverAddress3;
    @XmlElement(name = "ReceiverCompanyName", required = true, nillable = true)
    protected String receiverCompanyName;
    @XmlElement(name = "ReceiverContactName", required = true, nillable = true)
    protected String receiverContactName;
    @XmlElementRef(name = "ReceiverEmail", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverEmail;
    @XmlElementRef(name = "ReceiverFax", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverFax;
    @XmlElementRef(name = "ReceiverMob", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverMob;
    @XmlElement(name = "ReceiverPostcode", required = true, nillable = true)
    protected String receiverPostcode;
    @XmlElement(name = "ReceiverSuburb", required = true, nillable = true)
    protected String receiverSuburb;
    @XmlElementRef(name = "ReceiverTel", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> receiverTel;
    @XmlElementRef(name = "Ref1", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ref1;
    @XmlElementRef(name = "Ref2", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ref2;
    @XmlElementRef(name = "ReturnsCCEmail", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsCCEmail;
    @XmlElementRef(name = "ReturnsLabelPrintFlag", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsLabelPrintFlag;
    @XmlElementRef(name = "ReturnsReceiverEmail", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsReceiverEmail;
    @XmlElementRef(name = "ReturnsSenderContact", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsSenderContact;
    @XmlElementRef(name = "ReturnsSenderEmail", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsSenderEmail;
    @XmlElementRef(name = "ReturnsSenderTel", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsSenderTel;
    @XmlElementRef(name = "ReturnsServiceType", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> returnsServiceType;
    @XmlElement(name = "SenderAddress1", required = true, nillable = true)
    protected String senderAddress1;
    @XmlElementRef(name = "SenderAddress2", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderAddress2;
    @XmlElementRef(name = "SenderAddress3", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderAddress3;
    @XmlElement(name = "SenderCompany", required = true, nillable = true)
    protected String senderCompany;
    @XmlElementRef(name = "SenderEmail", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderEmail;
    @XmlElementRef(name = "SenderFax", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderFax;
    @XmlElementRef(name = "SenderMobile", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderMobile;
    @XmlElement(name = "SenderPostcode", required = true, nillable = true)
    protected String senderPostcode;
    @XmlElement(name = "SenderSuburb", required = true, nillable = true)
    protected String senderSuburb;
    @XmlElementRef(name = "SenderTel", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> senderTel;
    @XmlElement(name = "ServiceCode", required = true, nillable = true)
    protected String serviceCode;
    @XmlElementRef(name = "ServiceLabel", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serviceLabel;
    @XmlElementRef(name = "ServiceRef", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serviceRef;
    @XmlElementRef(name = "SmsNotifyFlag", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> smsNotifyFlag;
    @XmlElementRef(name = "SoftwareType", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> softwareType;
    @XmlElementRef(name = "StarTrackAcct", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> starTrackAcct;
    @XmlElementRef(name = "Sticker", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> sticker;
    @XmlElementRef(name = "SubRisk", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> subRisk;
    @XmlElementRef(name = "ThermalLabelPDF", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> thermalLabelPDF;
    @XmlElementRef(name = "UNNumber", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> unNumber;
    @XmlElementRef(name = "UnitType", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> unitType;
    @XmlElement(name = "Width")
    protected int width;
    @XmlElementRef(name = "Zone", namespace = "http://schemas.datacontract.org/2004/07/", type = JAXBElement.class, required = false)
    protected JAXBElement<String> zone;

    /**
     * Gets the value of the atl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getATL() {
        return atl;
    }

    /**
     * Sets the value of the atl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setATL(String value) {
        this.atl = value;
    }

    /**
     * Gets the value of the atlNum property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getATLNum() {
        return atlNum;
    }

    /**
     * Sets the value of the atlNum property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setATLNum(JAXBElement<String> value) {
        this.atlNum = value;
    }

    /**
     * Gets the value of the account property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccount(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the articleList property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getArticleList() {
        return articleList;
    }

    /**
     * Sets the value of the articleList property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setArticleList(JAXBElement<String> value) {
        this.articleList = value;
    }

    /**
     * Gets the value of the articles property.
     */
    public int getArticles() {
        return articles;
    }

    /**
     * Sets the value of the articles property.
     */
    public void setArticles(int value) {
        this.articles = value;
    }

    /**
     * Gets the value of the bookInDeliverFlag property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getBookInDeliverFlag() {
        return bookInDeliverFlag;
    }

    /**
     * Sets the value of the bookInDeliverFlag property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setBookInDeliverFlag(JAXBElement<String> value) {
        this.bookInDeliverFlag = value;
    }

    /**
     * Gets the value of the bookInNotAfter property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getBookInNotAfter() {
        return bookInNotAfter;
    }

    /**
     * Sets the value of the bookInNotAfter property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setBookInNotAfter(JAXBElement<String> value) {
        this.bookInNotAfter = value;
    }

    /**
     * Gets the value of the bookInNotBefore property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getBookInNotBefore() {
        return bookInNotBefore;
    }

    /**
     * Sets the value of the bookInNotBefore property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setBookInNotBefore(JAXBElement<String> value) {
        this.bookInNotBefore = value;
    }

    /**
     * Gets the value of the cid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCID() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCID(String value) {
        this.cid = value;
    }

    /**
     * Gets the value of the conId property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getConId() {
        return conId;
    }

    /**
     * Sets the value of the conId property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setConId(Integer value) {
        this.conId = value;
    }

    /**
     * Gets the value of the connotenum property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getConnotenum() {
        return connotenum;
    }

    /**
     * Sets the value of the connotenum property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setConnotenum(JAXBElement<String> value) {
        this.connotenum = value;
    }

    /**
     * Gets the value of the creatorName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * Sets the value of the creatorName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreatorName(String value) {
        this.creatorName = value;
    }

    /**
     * Gets the value of the creatorPhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCreatorPhone() {
        return creatorPhone;
    }

    /**
     * Sets the value of the creatorPhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreatorPhone(String value) {
        this.creatorPhone = value;
    }

    /**
     * Gets the value of the cubicVolume property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getCubicVolume() {
        return cubicVolume;
    }

    /**
     * Sets the value of the cubicVolume property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setCubicVolume(Integer value) {
        this.cubicVolume = value;
    }

    /**
     * Gets the value of the cubicWeight property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCubicWeight() {
        return cubicWeight;
    }

    /**
     * Sets the value of the cubicWeight property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCubicWeight(String value) {
        this.cubicWeight = value;
    }

    /**
     * Gets the value of the dgClass property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGClass() {
        return dgClass;
    }

    /**
     * Sets the value of the dgClass property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGClass(JAXBElement<String> value) {
        this.dgClass = value;
    }

    /**
     * Gets the value of the dgDeadWeight property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGDeadWeight() {
        return dgDeadWeight;
    }

    /**
     * Sets the value of the dgDeadWeight property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGDeadWeight(JAXBElement<String> value) {
        this.dgDeadWeight = value;
    }

    /**
     * Gets the value of the dgNumOuterPack property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGNumOuterPack() {
        return dgNumOuterPack;
    }

    /**
     * Sets the value of the dgNumOuterPack property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGNumOuterPack(JAXBElement<String> value) {
        this.dgNumOuterPack = value;
    }

    /**
     * Gets the value of the dgTechShipName property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGTechShipName() {
        return dgTechShipName;
    }

    /**
     * Sets the value of the dgTechShipName property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGTechShipName(JAXBElement<String> value) {
        this.dgTechShipName = value;
    }

    /**
     * Gets the value of the dgTradeName property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGTradeName() {
        return dgTradeName;
    }

    /**
     * Sets the value of the dgTradeName property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGTradeName(JAXBElement<String> value) {
        this.dgTradeName = value;
    }

    /**
     * Gets the value of the dgTypeOuterPack property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDGTypeOuterPack() {
        return dgTypeOuterPack;
    }

    /**
     * Sets the value of the dgTypeOuterPack property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDGTypeOuterPack(JAXBElement<String> value) {
        this.dgTypeOuterPack = value;
    }

    /**
     * Gets the value of the deadWeight property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeadWeight() {
        return deadWeight;
    }

    /**
     * Sets the value of the deadWeight property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeadWeight(String value) {
        this.deadWeight = value;
    }

    /**
     * Gets the value of the deliverOnDate property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDeliverOnDate() {
        return deliverOnDate;
    }

    /**
     * Sets the value of the deliverOnDate property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDeliverOnDate(JAXBElement<String> value) {
        this.deliverOnDate = value;
    }

    /**
     * Gets the value of the deliveryLines property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDeliveryLines() {
        return deliveryLines;
    }

    /**
     * Sets the value of the deliveryLines property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDeliveryLines(JAXBElement<String> value) {
        this.deliveryLines = value;
    }

    /**
     * Gets the value of the deliveryWindow property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDeliveryWindow() {
        return deliveryWindow;
    }

    /**
     * Sets the value of the deliveryWindow property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDeliveryWindow(JAXBElement<String> value) {
        this.deliveryWindow = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the despatchID property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDespatchID() {
        return despatchID;
    }

    /**
     * Sets the value of the despatchID property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDespatchID(JAXBElement<String> value) {
        this.despatchID = value;
    }

    /**
     * Gets the value of the emailAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setEmailAddress(JAXBElement<String> value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the emailLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmailLabels() {
        return emailLabels;
    }

    /**
     * Sets the value of the emailLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmailLabels(String value) {
        this.emailLabels = value;
    }

    /**
     * Gets the value of the emailNotifyFlag property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getEmailNotifyFlag() {
        return emailNotifyFlag;
    }

    /**
     * Sets the value of the emailNotifyFlag property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setEmailNotifyFlag(JAXBElement<String> value) {
        this.emailNotifyFlag = value;
    }

    /**
     * Gets the value of the fromPort property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getFromPort() {
        return fromPort;
    }

    /**
     * Sets the value of the fromPort property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setFromPort(JAXBElement<String> value) {
        this.fromPort = value;
    }

    /**
     * Gets the value of the fromZone property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getFromZone() {
        return fromZone;
    }

    /**
     * Sets the value of the fromZone property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setFromZone(JAXBElement<String> value) {
        this.fromZone = value;
    }

    /**
     * Gets the value of the height property.
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     */
    public void setHeight(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the invoiceList property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getInvoiceList() {
        return invoiceList;
    }

    /**
     * Sets the value of the invoiceList property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setInvoiceList(JAXBElement<String> value) {
        this.invoiceList = value;
    }

    /**
     * Gets the value of the length property.
     */
    public int getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     */
    public void setLength(int value) {
        this.length = value;
    }

    /**
     * Gets the value of the lithiumBatteries property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getLithiumBatteries() {
        return lithiumBatteries;
    }

    /**
     * Sets the value of the lithiumBatteries property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setLithiumBatteries(JAXBElement<String> value) {
        this.lithiumBatteries = value;
    }

    /**
     * Gets the value of the manifestDate property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getManifestDate() {
        return manifestDate;
    }

    /**
     * Sets the value of the manifestDate property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setManifestDate(JAXBElement<String> value) {
        this.manifestDate = value;
    }

    /**
     * Gets the value of the manifestNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getManifestNumber() {
        return manifestNumber;
    }

    /**
     * Sets the value of the manifestNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setManifestNumber(JAXBElement<String> value) {
        this.manifestNumber = value;
    }

    /**
     * Gets the value of the packingGroup property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getPackingGroup() {
        return packingGroup;
    }

    /**
     * Sets the value of the packingGroup property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setPackingGroup(JAXBElement<String> value) {
        this.packingGroup = value;
    }

    /**
     * Gets the value of the parcelProtection property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getParcelProtection() {
        return parcelProtection;
    }

    /**
     * Sets the value of the parcelProtection property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setParcelProtection(JAXBElement<String> value) {
        this.parcelProtection = value;
    }

    /**
     * Gets the value of the port property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setPort(JAXBElement<String> value) {
        this.port = value;
    }

    /**
     * Gets the value of the productCode property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setProductCode(JAXBElement<String> value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the receiverAddress1 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiverAddress1() {
        return receiverAddress1;
    }

    /**
     * Sets the value of the receiverAddress1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiverAddress1(String value) {
        this.receiverAddress1 = value;
    }

    /**
     * Gets the value of the receiverAddress2 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverAddress2() {
        return receiverAddress2;
    }

    /**
     * Sets the value of the receiverAddress2 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverAddress2(JAXBElement<String> value) {
        this.receiverAddress2 = value;
    }

    /**
     * Gets the value of the receiverAddress3 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverAddress3() {
        return receiverAddress3;
    }

    /**
     * Sets the value of the receiverAddress3 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverAddress3(JAXBElement<String> value) {
        this.receiverAddress3 = value;
    }

    /**
     * Gets the value of the receiverCompanyName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiverCompanyName() {
        return receiverCompanyName;
    }

    /**
     * Sets the value of the receiverCompanyName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiverCompanyName(String value) {
        this.receiverCompanyName = value;
    }

    /**
     * Gets the value of the receiverContactName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiverContactName() {
        return receiverContactName;
    }

    /**
     * Sets the value of the receiverContactName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiverContactName(String value) {
        this.receiverContactName = value;
    }

    /**
     * Gets the value of the receiverEmail property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverEmail() {
        return receiverEmail;
    }

    /**
     * Sets the value of the receiverEmail property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverEmail(JAXBElement<String> value) {
        this.receiverEmail = value;
    }

    /**
     * Gets the value of the receiverFax property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverFax() {
        return receiverFax;
    }

    /**
     * Sets the value of the receiverFax property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverFax(JAXBElement<String> value) {
        this.receiverFax = value;
    }

    /**
     * Gets the value of the receiverMob property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverMob() {
        return receiverMob;
    }

    /**
     * Sets the value of the receiverMob property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverMob(JAXBElement<String> value) {
        this.receiverMob = value;
    }

    /**
     * Gets the value of the receiverPostcode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiverPostcode() {
        return receiverPostcode;
    }

    /**
     * Sets the value of the receiverPostcode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiverPostcode(String value) {
        this.receiverPostcode = value;
    }

    /**
     * Gets the value of the receiverSuburb property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiverSuburb() {
        return receiverSuburb;
    }

    /**
     * Sets the value of the receiverSuburb property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiverSuburb(String value) {
        this.receiverSuburb = value;
    }

    /**
     * Gets the value of the receiverTel property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReceiverTel() {
        return receiverTel;
    }

    /**
     * Sets the value of the receiverTel property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReceiverTel(JAXBElement<String> value) {
        this.receiverTel = value;
    }

    /**
     * Gets the value of the ref1 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getRef1() {
        return ref1;
    }

    /**
     * Sets the value of the ref1 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setRef1(JAXBElement<String> value) {
        this.ref1 = value;
    }

    /**
     * Gets the value of the ref2 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getRef2() {
        return ref2;
    }

    /**
     * Sets the value of the ref2 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setRef2(JAXBElement<String> value) {
        this.ref2 = value;
    }

    /**
     * Gets the value of the returnsCCEmail property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsCCEmail() {
        return returnsCCEmail;
    }

    /**
     * Sets the value of the returnsCCEmail property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsCCEmail(JAXBElement<String> value) {
        this.returnsCCEmail = value;
    }

    /**
     * Gets the value of the returnsLabelPrintFlag property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsLabelPrintFlag() {
        return returnsLabelPrintFlag;
    }

    /**
     * Sets the value of the returnsLabelPrintFlag property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsLabelPrintFlag(JAXBElement<String> value) {
        this.returnsLabelPrintFlag = value;
    }

    /**
     * Gets the value of the returnsReceiverEmail property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsReceiverEmail() {
        return returnsReceiverEmail;
    }

    /**
     * Sets the value of the returnsReceiverEmail property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsReceiverEmail(JAXBElement<String> value) {
        this.returnsReceiverEmail = value;
    }

    /**
     * Gets the value of the returnsSenderContact property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsSenderContact() {
        return returnsSenderContact;
    }

    /**
     * Sets the value of the returnsSenderContact property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsSenderContact(JAXBElement<String> value) {
        this.returnsSenderContact = value;
    }

    /**
     * Gets the value of the returnsSenderEmail property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsSenderEmail() {
        return returnsSenderEmail;
    }

    /**
     * Sets the value of the returnsSenderEmail property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsSenderEmail(JAXBElement<String> value) {
        this.returnsSenderEmail = value;
    }

    /**
     * Gets the value of the returnsSenderTel property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsSenderTel() {
        return returnsSenderTel;
    }

    /**
     * Sets the value of the returnsSenderTel property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsSenderTel(JAXBElement<String> value) {
        this.returnsSenderTel = value;
    }

    /**
     * Gets the value of the returnsServiceType property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getReturnsServiceType() {
        return returnsServiceType;
    }

    /**
     * Sets the value of the returnsServiceType property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setReturnsServiceType(JAXBElement<String> value) {
        this.returnsServiceType = value;
    }

    /**
     * Gets the value of the senderAddress1 property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderAddress1() {
        return senderAddress1;
    }

    /**
     * Sets the value of the senderAddress1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderAddress1(String value) {
        this.senderAddress1 = value;
    }

    /**
     * Gets the value of the senderAddress2 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderAddress2() {
        return senderAddress2;
    }

    /**
     * Sets the value of the senderAddress2 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderAddress2(JAXBElement<String> value) {
        this.senderAddress2 = value;
    }

    /**
     * Gets the value of the senderAddress3 property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderAddress3() {
        return senderAddress3;
    }

    /**
     * Sets the value of the senderAddress3 property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderAddress3(JAXBElement<String> value) {
        this.senderAddress3 = value;
    }

    /**
     * Gets the value of the senderCompany property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderCompany() {
        return senderCompany;
    }

    /**
     * Sets the value of the senderCompany property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderCompany(String value) {
        this.senderCompany = value;
    }

    /**
     * Gets the value of the senderEmail property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderEmail(JAXBElement<String> value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the senderFax property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderFax() {
        return senderFax;
    }

    /**
     * Sets the value of the senderFax property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderFax(JAXBElement<String> value) {
        this.senderFax = value;
    }

    /**
     * Gets the value of the senderMobile property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderMobile() {
        return senderMobile;
    }

    /**
     * Sets the value of the senderMobile property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderMobile(JAXBElement<String> value) {
        this.senderMobile = value;
    }

    /**
     * Gets the value of the senderPostcode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderPostcode() {
        return senderPostcode;
    }

    /**
     * Sets the value of the senderPostcode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderPostcode(String value) {
        this.senderPostcode = value;
    }

    /**
     * Gets the value of the senderSuburb property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSenderSuburb() {
        return senderSuburb;
    }

    /**
     * Sets the value of the senderSuburb property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSenderSuburb(String value) {
        this.senderSuburb = value;
    }

    /**
     * Gets the value of the senderTel property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSenderTel() {
        return senderTel;
    }

    /**
     * Sets the value of the senderTel property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSenderTel(JAXBElement<String> value) {
        this.senderTel = value;
    }

    /**
     * Gets the value of the serviceCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the serviceLabel property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getServiceLabel() {
        return serviceLabel;
    }

    /**
     * Sets the value of the serviceLabel property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setServiceLabel(JAXBElement<String> value) {
        this.serviceLabel = value;
    }

    /**
     * Gets the value of the serviceRef property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getServiceRef() {
        return serviceRef;
    }

    /**
     * Sets the value of the serviceRef property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setServiceRef(JAXBElement<String> value) {
        this.serviceRef = value;
    }

    /**
     * Gets the value of the smsNotifyFlag property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSmsNotifyFlag() {
        return smsNotifyFlag;
    }

    /**
     * Sets the value of the smsNotifyFlag property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSmsNotifyFlag(JAXBElement<String> value) {
        this.smsNotifyFlag = value;
    }

    /**
     * Gets the value of the softwareType property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSoftwareType() {
        return softwareType;
    }

    /**
     * Sets the value of the softwareType property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSoftwareType(JAXBElement<String> value) {
        this.softwareType = value;
    }

    /**
     * Gets the value of the starTrackAcct property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getStarTrackAcct() {
        return starTrackAcct;
    }

    /**
     * Sets the value of the starTrackAcct property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setStarTrackAcct(JAXBElement<String> value) {
        this.starTrackAcct = value;
    }

    /**
     * Gets the value of the sticker property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSticker() {
        return sticker;
    }

    /**
     * Sets the value of the sticker property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSticker(JAXBElement<String> value) {
        this.sticker = value;
    }

    /**
     * Gets the value of the subRisk property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSubRisk() {
        return subRisk;
    }

    /**
     * Sets the value of the subRisk property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSubRisk(JAXBElement<String> value) {
        this.subRisk = value;
    }

    /**
     * Gets the value of the thermalLabelPDF property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getThermalLabelPDF() {
        return thermalLabelPDF;
    }

    /**
     * Sets the value of the thermalLabelPDF property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setThermalLabelPDF(JAXBElement<String> value) {
        this.thermalLabelPDF = value;
    }

    /**
     * Gets the value of the unNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getUNNumber() {
        return unNumber;
    }

    /**
     * Sets the value of the unNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setUNNumber(JAXBElement<String> value) {
        this.unNumber = value;
    }

    /**
     * Gets the value of the unitType property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setUnitType(JAXBElement<String> value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the width property.
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the zone property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getZone() {
        return zone;
    }

    /**
     * Sets the value of the zone property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setZone(JAXBElement<String> value) {
        this.zone = value;
    }

}
