//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:24:43 AM ICT 
//


package com.gms.delivery.tnt.xmlpi.label.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for consignmentResponseType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="consignmentResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pieceLabelData" type="{}pieceRoutingLabelType" maxOccurs="99"/>
 *         &lt;element name="consignmentLabelData" type="{}consignmentRoutingLabelType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consignmentResponseType", propOrder = {
        "pieceLabelData",
        "consignmentLabelData"
})
public class ConsignmentResponseType {

    @XmlElement(required = true)
    protected List<PieceRoutingLabelType> pieceLabelData;
    @XmlElement(required = true)
    protected ConsignmentRoutingLabelType consignmentLabelData;
    @XmlAttribute(name = "key", required = true)
    protected String key;

    /**
     * Gets the value of the pieceLabelData property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pieceLabelData property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPieceLabelData().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PieceRoutingLabelType }
     */
    public List<PieceRoutingLabelType> getPieceLabelData() {
        if (pieceLabelData == null) {
            pieceLabelData = new ArrayList<PieceRoutingLabelType>();
        }
        return this.pieceLabelData;
    }

    /**
     * Gets the value of the consignmentLabelData property.
     *
     * @return possible object is
     * {@link ConsignmentRoutingLabelType }
     */
    public ConsignmentRoutingLabelType getConsignmentLabelData() {
        return consignmentLabelData;
    }

    /**
     * Sets the value of the consignmentLabelData property.
     *
     * @param value allowed object is
     *              {@link ConsignmentRoutingLabelType }
     */
    public void setConsignmentLabelData(ConsignmentRoutingLabelType value) {
        this.consignmentLabelData = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKey(String value) {
        this.key = value;
    }

}
