//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 10:24:43 AM ICT 
//


package com.gms.delivery.tnt.xmlpi.label.response;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for renderInstructionsType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="renderInstructionsType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attGroup ref="{}renderInstructionsAttributesType"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "renderInstructionsType", propOrder = {
        "value"
})
public class RenderInstructionsType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "code", required = true)
    protected String code;
    @XmlAttribute(name = "renderInstructions", required = true)
    protected String renderInstructions;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the renderInstructions property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRenderInstructions() {
        return renderInstructions;
    }

    /**
     * Sets the value of the renderInstructions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRenderInstructions(String value) {
        this.renderInstructions = value;
    }

}
