//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 11:30:46 AM ICT 
//

package com.gms.delivery.startrack.xmlpi.tempuri;

import com.gms.delivery.startrack.xmlpi.aaecreatebooking.AaEBookingResult;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreateBookingResult" type="{http://schemas.datacontract.org/2004/07/AaECreateBooking}AaEBookingResult" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"createBookingResult"})
@XmlRootElement(name = "CreateBookingResponse")
public class CreateBookingResponse {

    @XmlElementRef(name = "CreateBookingResult", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<AaEBookingResult> createBookingResult;

    /**
     * Gets the value of the createBookingResult property.
     *
     * @return possible object is {@link JAXBElement }{@code <}{@link AaEBookingResult }{@code >}
     */
    public JAXBElement<AaEBookingResult> getCreateBookingResult() {
        return createBookingResult;
    }

    /**
     * Sets the value of the createBookingResult property.
     *
     * @param value allowed object is {@link JAXBElement }{@code <}{@link AaEBookingResult }{@code >}
     */
    public void setCreateBookingResult(JAXBElement<AaEBookingResult> value) {
        this.createBookingResult = value;
    }

}
