//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 04:23:02 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Commodity complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Commodity"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommodityCode" type="{http://www.dhl.com/datatypes_global}CommodityCode"/&gt;
 *         &lt;element name="CommodityName" type="{http://www.dhl.com/datatypes_global}CommodityName" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commodity", propOrder = {
        "commodityCode",
        "commodityName"
})
public class Commodity {

    @XmlElement(name = "CommodityCode", required = true)
    protected String commodityCode;
    @XmlElement(name = "CommodityName")
    protected String commodityName;

    /**
     * Gets the value of the commodityCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * Sets the value of the commodityCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommodityCode(String value) {
        this.commodityCode = value;
    }

    /**
     * Gets the value of the commodityName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * Sets the value of the commodityName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommodityName(String value) {
        this.commodityName = value;
    }

}
