//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 04:23:02 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputFormat.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OutputFormat"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PDF"/&gt;
 *     &lt;enumeration value="PL2"/&gt;
 *     &lt;enumeration value="ZPL2"/&gt;
 *     &lt;enumeration value="JPG"/&gt;
 *     &lt;enumeration value="PNG"/&gt;
 *     &lt;enumeration value="EPL2"/&gt;
 *     &lt;enumeration value="EPLN"/&gt;
 *     &lt;enumeration value="ZPLN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "OutputFormat")
@XmlEnum
public enum OutputFormat {

    PDF("PDF"),
    @XmlEnumValue("PL2")
    PL_2("PL2"),
    @XmlEnumValue("ZPL2")
    ZPL_2("ZPL2"),
    JPG("JPG"),
    PNG("PNG"),
    @XmlEnumValue("EPL2")
    EPL_2("EPL2"),
    EPLN("EPLN"),
    ZPLN("ZPLN");
    private final String value;

    OutputFormat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OutputFormat fromValue(String v) {
        for (OutputFormat c : OutputFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
