//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 04:23:02 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PackageType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;length value="2"/&gt;
 *     &lt;enumeration value="BD"/&gt;
 *     &lt;enumeration value="BP"/&gt;
 *     &lt;enumeration value="CP"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="DF"/&gt;
 *     &lt;enumeration value="DM"/&gt;
 *     &lt;enumeration value="ED"/&gt;
 *     &lt;enumeration value="EE"/&gt;
 *     &lt;enumeration value="FR"/&gt;
 *     &lt;enumeration value="JB"/&gt;
 *     &lt;enumeration value="JD"/&gt;
 *     &lt;enumeration value="JJ"/&gt;
 *     &lt;enumeration value="JP"/&gt;
 *     &lt;enumeration value="OD"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="YP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "PackageType")
@XmlEnum
public enum PackageType {

    BD,
    BP,
    CP,
    DC,
    DF,
    DM,
    ED,
    EE,
    FR,
    JB,
    JD,
    JJ,
    JP,
    OD,
    PA,
    YP;

    public String value() {
        return name();
    }

    public static PackageType fromValue(String v) {
        return valueOf(v);
    }

}
