//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.22 at 04:23:02 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SpecialService complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="SpecialService"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SpecialServiceType" type="{http://www.dhl.com/datatypes_global}SpecialServiceType" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddress" type="{http://www.dhl.com/datatypes_global}CommunicationAddress" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationType" type="{http://www.dhl.com/datatypes_global}CommunicationType" minOccurs="0"/&gt;
 *         &lt;element name="ChargeValue" type="{http://www.dhl.com/datatypes_global}Money" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyCode" type="{http://www.dhl.com/datatypes_global}CurrencyCode" minOccurs="0"/&gt;
 *         &lt;element name="IsWaived" type="{http://www.dhl.com/datatypes_global}YesNo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialService", propOrder = {
        "specialServiceType",
        "communicationAddress",
        "communicationType",
        "chargeValue",
        "currencyCode",
        "isWaived"
})
public class SpecialService {

    @XmlElement(name = "SpecialServiceType")
    protected String specialServiceType;
    @XmlElement(name = "CommunicationAddress")
    protected String communicationAddress;
    @XmlElement(name = "CommunicationType")
    @XmlSchemaType(name = "string")
    protected CommunicationType communicationType;
    @XmlElement(name = "ChargeValue")
    protected Float chargeValue;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "IsWaived")
    @XmlSchemaType(name = "string")
    protected YesNo isWaived;

    /**
     * Gets the value of the specialServiceType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSpecialServiceType() {
        return specialServiceType;
    }

    /**
     * Sets the value of the specialServiceType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSpecialServiceType(String value) {
        this.specialServiceType = value;
    }

    /**
     * Gets the value of the communicationAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCommunicationAddress() {
        return communicationAddress;
    }

    /**
     * Sets the value of the communicationAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommunicationAddress(String value) {
        this.communicationAddress = value;
    }

    /**
     * Gets the value of the communicationType property.
     *
     * @return possible object is
     * {@link CommunicationType }
     */
    public CommunicationType getCommunicationType() {
        return communicationType;
    }

    /**
     * Sets the value of the communicationType property.
     *
     * @param value allowed object is
     *              {@link CommunicationType }
     */
    public void setCommunicationType(CommunicationType value) {
        this.communicationType = value;
    }

    /**
     * Gets the value of the chargeValue property.
     *
     * @return possible object is
     * {@link Float }
     */
    public Float getChargeValue() {
        return chargeValue;
    }

    /**
     * Sets the value of the chargeValue property.
     *
     * @param value allowed object is
     *              {@link Float }
     */
    public void setChargeValue(Float value) {
        this.chargeValue = value;
    }

    /**
     * Gets the value of the currencyCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the isWaived property.
     *
     * @return possible object is
     * {@link YesNo }
     */
    public YesNo getIsWaived() {
        return isWaived;
    }

    /**
     * Sets the value of the isWaived property.
     *
     * @param value allowed object is
     *              {@link YesNo }
     */
    public void setIsWaived(YesNo value) {
        this.isWaived = value;
    }

}
