//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 03:08:02 PM ICT 
//


package com.gms.delivery.startrack.xmlpi.tracking.response;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for consignment complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="consignment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="references" type="{}references" maxOccurs="unbounded"/&gt;
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="receiver" type="{}receiver"/&gt;
 *         &lt;element name="sender" type="{}sender"/&gt;
 *         &lt;element name="despatchLocationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statusHistory" type="{}statusHistory" maxOccurs="unbounded"/&gt;
 *         &lt;element name="trackingEvents" type="{}trackingEvents" maxOccurs="unbounded"/&gt;
 *         &lt;element name="lineItems" type="{}lineItems"/&gt;
 *         &lt;element name="image" type="{}image"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="billedInd" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="carrierCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="consolidate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="consolidateSendersReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="deliveryDepot" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="despatchDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="despatchDepot" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="despatchNotification" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="driverCube" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="etaDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lastStatusDateTime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lock_seq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="payerAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="payerType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="podSignatoryName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="podSignature" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="requestService" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="totalQuantity" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="totalVolume" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="totalWeight" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="unitType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="userName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consignment", propOrder = {
        "references",
        "serviceCode",
        "receiver",
        "sender",
        "despatchLocationCode",
        "statusHistory",
        "trackingEvents",
        "lineItems",
        "image"
})
public class Consignment {

    @XmlElement(required = true)
    protected List<References> references;
    @XmlElement(required = true)
    protected String serviceCode;
    @XmlElement(required = true)
    protected Receiver receiver;
    @XmlElement(required = true)
    protected Sender sender;
    @XmlElement(required = true)
    protected String despatchLocationCode;
    @XmlElement(required = true)
    protected List<StatusHistory> statusHistory;
    @XmlElement(required = true)
    protected List<TrackingEvents> trackingEvents;
    @XmlElement(required = true)
    protected LineItems lineItems;
    @XmlElement(required = true)
    protected Image image;
    @XmlAttribute(name = "billedInd")
    protected String billedInd;
    @XmlAttribute(name = "carrierCode")
    protected String carrierCode;
    @XmlAttribute(name = "consolidate")
    protected String consolidate;
    @XmlAttribute(name = "consolidateSendersReference")
    protected String consolidateSendersReference;
    @XmlAttribute(name = "deliveryDepot")
    protected String deliveryDepot;
    @XmlAttribute(name = "despatchDate")
    protected String despatchDate;
    @XmlAttribute(name = "despatchDepot")
    protected String despatchDepot;
    @XmlAttribute(name = "despatchNotification")
    protected String despatchNotification;
    @XmlAttribute(name = "driverCube")
    protected Double driverCube;
    @XmlAttribute(name = "etaDate")
    protected String etaDate;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "lastStatusDateTime")
    protected String lastStatusDateTime;
    @XmlAttribute(name = "lock_seq")
    protected Integer lockSeq;
    @XmlAttribute(name = "payerAccountNumber")
    protected String payerAccountNumber;
    @XmlAttribute(name = "payerType")
    protected String payerType;
    @XmlAttribute(name = "podSignatoryName")
    protected String podSignatoryName;
    @XmlAttribute(name = "podSignature")
    protected String podSignature;
    @XmlAttribute(name = "requestService")
    protected String requestService;
    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "totalQuantity")
    protected Integer totalQuantity;
    @XmlAttribute(name = "totalVolume")
    protected Double totalVolume;
    @XmlAttribute(name = "totalWeight")
    protected Double totalWeight;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "unitType")
    protected String unitType;
    @XmlAttribute(name = "userName")
    protected String userName;

    /**
     * Gets the value of the references property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferences().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link References }
     */
    public List<References> getReferences() {
        if (references == null) {
            references = new ArrayList<References>();
        }
        return this.references;
    }

    /**
     * Gets the value of the serviceCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the receiver property.
     *
     * @return possible object is
     * {@link Receiver }
     */
    public Receiver getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     *
     * @param value allowed object is
     *              {@link Receiver }
     */
    public void setReceiver(Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link Sender }
     */
    public Sender getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link Sender }
     */
    public void setSender(Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the despatchLocationCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDespatchLocationCode() {
        return despatchLocationCode;
    }

    /**
     * Sets the value of the despatchLocationCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDespatchLocationCode(String value) {
        this.despatchLocationCode = value;
    }

    /**
     * Gets the value of the statusHistory property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusHistory property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusHistory().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusHistory }
     */
    public List<StatusHistory> getStatusHistory() {
        if (statusHistory == null) {
            statusHistory = new ArrayList<StatusHistory>();
        }
        return this.statusHistory;
    }

    /**
     * Gets the value of the trackingEvents property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trackingEvents property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrackingEvents().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrackingEvents }
     */
    public List<TrackingEvents> getTrackingEvents() {
        if (trackingEvents == null) {
            trackingEvents = new ArrayList<TrackingEvents>();
        }
        return this.trackingEvents;
    }

    /**
     * Gets the value of the lineItems property.
     *
     * @return possible object is
     * {@link LineItems }
     */
    public LineItems getLineItems() {
        return lineItems;
    }

    /**
     * Sets the value of the lineItems property.
     *
     * @param value allowed object is
     *              {@link LineItems }
     */
    public void setLineItems(LineItems value) {
        this.lineItems = value;
    }

    /**
     * Gets the value of the image property.
     *
     * @return possible object is
     * {@link Image }
     */
    public Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     *
     * @param value allowed object is
     *              {@link Image }
     */
    public void setImage(Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the billedInd property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBilledInd() {
        return billedInd;
    }

    /**
     * Sets the value of the billedInd property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBilledInd(String value) {
        this.billedInd = value;
    }

    /**
     * Gets the value of the carrierCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * Sets the value of the carrierCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCarrierCode(String value) {
        this.carrierCode = value;
    }

    /**
     * Gets the value of the consolidate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConsolidate() {
        return consolidate;
    }

    /**
     * Sets the value of the consolidate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConsolidate(String value) {
        this.consolidate = value;
    }

    /**
     * Gets the value of the consolidateSendersReference property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConsolidateSendersReference() {
        return consolidateSendersReference;
    }

    /**
     * Sets the value of the consolidateSendersReference property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConsolidateSendersReference(String value) {
        this.consolidateSendersReference = value;
    }

    /**
     * Gets the value of the deliveryDepot property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeliveryDepot() {
        return deliveryDepot;
    }

    /**
     * Sets the value of the deliveryDepot property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeliveryDepot(String value) {
        this.deliveryDepot = value;
    }

    /**
     * Gets the value of the despatchDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDespatchDate() {
        return despatchDate;
    }

    /**
     * Sets the value of the despatchDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDespatchDate(String value) {
        this.despatchDate = value;
    }

    /**
     * Gets the value of the despatchDepot property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDespatchDepot() {
        return despatchDepot;
    }

    /**
     * Sets the value of the despatchDepot property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDespatchDepot(String value) {
        this.despatchDepot = value;
    }

    /**
     * Gets the value of the despatchNotification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDespatchNotification() {
        return despatchNotification;
    }

    /**
     * Sets the value of the despatchNotification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDespatchNotification(String value) {
        this.despatchNotification = value;
    }

    /**
     * Gets the value of the driverCube property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getDriverCube() {
        return driverCube;
    }

    /**
     * Sets the value of the driverCube property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setDriverCube(Double value) {
        this.driverCube = value;
    }

    /**
     * Gets the value of the etaDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEtaDate() {
        return etaDate;
    }

    /**
     * Sets the value of the etaDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEtaDate(String value) {
        this.etaDate = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lastStatusDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastStatusDateTime() {
        return lastStatusDateTime;
    }

    /**
     * Sets the value of the lastStatusDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastStatusDateTime(String value) {
        this.lastStatusDateTime = value;
    }

    /**
     * Gets the value of the lockSeq property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getLockSeq() {
        return lockSeq;
    }

    /**
     * Sets the value of the lockSeq property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setLockSeq(Integer value) {
        this.lockSeq = value;
    }

    /**
     * Gets the value of the payerAccountNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPayerAccountNumber() {
        return payerAccountNumber;
    }

    /**
     * Sets the value of the payerAccountNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPayerAccountNumber(String value) {
        this.payerAccountNumber = value;
    }

    /**
     * Gets the value of the payerType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPayerType() {
        return payerType;
    }

    /**
     * Sets the value of the payerType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPayerType(String value) {
        this.payerType = value;
    }

    /**
     * Gets the value of the podSignatoryName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPodSignatoryName() {
        return podSignatoryName;
    }

    /**
     * Sets the value of the podSignatoryName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPodSignatoryName(String value) {
        this.podSignatoryName = value;
    }

    /**
     * Gets the value of the podSignature property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPodSignature() {
        return podSignature;
    }

    /**
     * Sets the value of the podSignature property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPodSignature(String value) {
        this.podSignature = value;
    }

    /**
     * Gets the value of the requestService property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRequestService() {
        return requestService;
    }

    /**
     * Sets the value of the requestService property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRequestService(String value) {
        this.requestService = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the totalQuantity property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * Sets the value of the totalQuantity property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setTotalQuantity(Integer value) {
        this.totalQuantity = value;
    }

    /**
     * Gets the value of the totalVolume property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getTotalVolume() {
        return totalVolume;
    }

    /**
     * Sets the value of the totalVolume property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setTotalVolume(Double value) {
        this.totalVolume = value;
    }

    /**
     * Gets the value of the totalWeight property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getTotalWeight() {
        return totalWeight;
    }

    /**
     * Sets the value of the totalWeight property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setTotalWeight(Double value) {
        this.totalWeight = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the unitType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnitType(String value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the userName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserName(String value) {
        this.userName = value;
    }

}
