//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 03:08:02 PM ICT 
//


package com.gms.delivery.startrack.xmlpi.tracking.response;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for freightItemTrackingEvent complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="freightItemTrackingEvent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="scanner" type="{}scanner"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="eventDateTime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="scanMode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="transitState" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "freightItemTrackingEvent", propOrder = {
        "scanner"
})
public class FreightItemTrackingEvent {

    @XmlElement(required = true)
    protected Scanner scanner;
    @XmlAttribute(name = "eventDateTime")
    protected String eventDateTime;
    @XmlAttribute(name = "scanMode")
    protected String scanMode;
    @XmlAttribute(name = "transitState")
    protected String transitState;

    /**
     * Gets the value of the scanner property.
     *
     * @return possible object is
     * {@link Scanner }
     */
    public Scanner getScanner() {
        return scanner;
    }

    /**
     * Sets the value of the scanner property.
     *
     * @param value allowed object is
     *              {@link Scanner }
     */
    public void setScanner(Scanner value) {
        this.scanner = value;
    }

    /**
     * Gets the value of the eventDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEventDateTime() {
        return eventDateTime;
    }

    /**
     * Sets the value of the eventDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEventDateTime(String value) {
        this.eventDateTime = value;
    }

    /**
     * Gets the value of the scanMode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanMode() {
        return scanMode;
    }

    /**
     * Sets the value of the scanMode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanMode(String value) {
        this.scanMode = value;
    }

    /**
     * Gets the value of the transitState property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransitState() {
        return transitState;
    }

    /**
     * Sets the value of the transitState property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransitState(String value) {
        this.transitState = value;
    }

}
