//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.28 at 05:13:39 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.tracking.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchCriteria">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;sequence>
 *                     &lt;element ref="{}Account"/>
 *                     &lt;element ref="{}Period"/>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;choice>
 *                       &lt;sequence maxOccurs="50">
 *                         &lt;element name="AlternativeConsignmentNumber" type="{}NonZeroLengthString"/>
 *                       &lt;/sequence>
 *                       &lt;sequence maxOccurs="50">
 *                         &lt;element name="ConsignmentNumber" type="{}NonZeroLengthString"/>
 *                       &lt;/sequence>
 *                       &lt;sequence maxOccurs="50">
 *                         &lt;element name="CustomerReference" type="{}NonZeroLengthString"/>
 *                       &lt;/sequence>
 *                       &lt;sequence maxOccurs="50">
 *                         &lt;element name="PieceReference" type="{}NonZeroLengthString"/>
 *                       &lt;/sequence>
 *                     &lt;/choice>
 *                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                       &lt;element ref="{}Account" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;element ref="{}Period" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *                 &lt;attribute name="marketType" type="{}MarketTypeType" />
 *                 &lt;attribute name="originCountry" type="{}CountryCodeType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LevelOfDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Complete">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="originAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="destinationAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="shipment" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="podImage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Summary" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="locale" type="{}LocaleType" />
 *       &lt;attribute name="version" type="{}VersionType" default="3.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "searchCriteria",
        "levelOfDetail"
})
@XmlRootElement(name = "TrackRequest")
public class TrackRequest {

    @XmlElement(name = "SearchCriteria", required = true)
    protected TrackRequest.SearchCriteria searchCriteria;
    @XmlElement(name = "LevelOfDetail")
    protected TrackRequest.LevelOfDetail levelOfDetail;
    @XmlAttribute(name = "locale")
    protected String locale;
    @XmlAttribute(name = "version")
    protected Float version;

    /**
     * Gets the value of the searchCriteria property.
     *
     * @return possible object is
     * {@link TrackRequest.SearchCriteria }
     */
    public TrackRequest.SearchCriteria getSearchCriteria() {
        return searchCriteria;
    }

    /**
     * Sets the value of the searchCriteria property.
     *
     * @param value allowed object is
     *              {@link TrackRequest.SearchCriteria }
     */
    public void setSearchCriteria(TrackRequest.SearchCriteria value) {
        this.searchCriteria = value;
    }

    /**
     * Gets the value of the levelOfDetail property.
     *
     * @return possible object is
     * {@link TrackRequest.LevelOfDetail }
     */
    public TrackRequest.LevelOfDetail getLevelOfDetail() {
        return levelOfDetail;
    }

    /**
     * Sets the value of the levelOfDetail property.
     *
     * @param value allowed object is
     *              {@link TrackRequest.LevelOfDetail }
     */
    public void setLevelOfDetail(TrackRequest.LevelOfDetail value) {
        this.levelOfDetail = value;
    }

    /**
     * Gets the value of the locale property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link Float }
     */
    public float getVersion() {
        if (version == null) {
            return 3.0F;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link Float }
     */
    public void setVersion(Float value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Complete">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="originAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="destinationAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="shipment" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="podImage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Summary" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "complete",
            "summary"
    })
    public static class LevelOfDetail {

        @XmlElement(name = "Complete")
        protected TrackRequest.LevelOfDetail.Complete complete;
        @XmlElement(name = "Summary")
        protected Object summary;

        /**
         * Gets the value of the complete property.
         *
         * @return possible object is
         * {@link TrackRequest.LevelOfDetail.Complete }
         */
        public TrackRequest.LevelOfDetail.Complete getComplete() {
            return complete;
        }

        /**
         * Sets the value of the complete property.
         *
         * @param value allowed object is
         *              {@link TrackRequest.LevelOfDetail.Complete }
         */
        public void setComplete(TrackRequest.LevelOfDetail.Complete value) {
            this.complete = value;
        }

        /**
         * Gets the value of the summary property.
         *
         * @return possible object is
         * {@link Object }
         */
        public Object getSummary() {
            return summary;
        }

        /**
         * Sets the value of the summary property.
         *
         * @param value allowed object is
         *              {@link Object }
         */
        public void setSummary(Object value) {
            this.summary = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="originAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="destinationAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="shipment" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="podImage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Complete {

            @XmlAttribute(name = "originAddress")
            protected Boolean originAddress;
            @XmlAttribute(name = "destinationAddress")
            protected Boolean destinationAddress;
            @XmlAttribute(name = "shipment")
            protected Boolean shipment;
            @XmlAttribute(name = "package")
            protected Boolean _package;
            @XmlAttribute(name = "podImage")
            protected Boolean podImage;

            /**
             * Gets the value of the originAddress property.
             *
             * @return possible object is
             * {@link Boolean }
             */
            public boolean isOriginAddress() {
                if (originAddress == null) {
                    return false;
                } else {
                    return originAddress;
                }
            }

            /**
             * Sets the value of the originAddress property.
             *
             * @param value allowed object is
             *              {@link Boolean }
             */
            public void setOriginAddress(Boolean value) {
                this.originAddress = value;
            }

            /**
             * Gets the value of the destinationAddress property.
             *
             * @return possible object is
             * {@link Boolean }
             */
            public boolean isDestinationAddress() {
                if (destinationAddress == null) {
                    return false;
                } else {
                    return destinationAddress;
                }
            }

            /**
             * Sets the value of the destinationAddress property.
             *
             * @param value allowed object is
             *              {@link Boolean }
             */
            public void setDestinationAddress(Boolean value) {
                this.destinationAddress = value;
            }

            /**
             * Gets the value of the shipment property.
             *
             * @return possible object is
             * {@link Boolean }
             */
            public boolean isShipment() {
                if (shipment == null) {
                    return false;
                } else {
                    return shipment;
                }
            }

            /**
             * Sets the value of the shipment property.
             *
             * @param value allowed object is
             *              {@link Boolean }
             */
            public void setShipment(Boolean value) {
                this.shipment = value;
            }

            /**
             * Gets the value of the package property.
             *
             * @return possible object is
             * {@link Boolean }
             */
            public boolean isPackage() {
                if (_package == null) {
                    return false;
                } else {
                    return _package;
                }
            }

            /**
             * Sets the value of the package property.
             *
             * @param value allowed object is
             *              {@link Boolean }
             */
            public void setPackage(Boolean value) {
                this._package = value;
            }

            /**
             * Gets the value of the podImage property.
             *
             * @return possible object is
             * {@link Boolean }
             */
            public boolean isPodImage() {
                if (podImage == null) {
                    return false;
                } else {
                    return podImage;
                }
            }

            /**
             * Sets the value of the podImage property.
             *
             * @param value allowed object is
             *              {@link Boolean }
             */
            public void setPodImage(Boolean value) {
                this.podImage = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;sequence>
     *           &lt;element ref="{}Account"/>
     *           &lt;element ref="{}Period"/>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;choice>
     *             &lt;sequence maxOccurs="50">
     *               &lt;element name="AlternativeConsignmentNumber" type="{}NonZeroLengthString"/>
     *             &lt;/sequence>
     *             &lt;sequence maxOccurs="50">
     *               &lt;element name="ConsignmentNumber" type="{}NonZeroLengthString"/>
     *             &lt;/sequence>
     *             &lt;sequence maxOccurs="50">
     *               &lt;element name="CustomerReference" type="{}NonZeroLengthString"/>
     *             &lt;/sequence>
     *             &lt;sequence maxOccurs="50">
     *               &lt;element name="PieceReference" type="{}NonZeroLengthString"/>
     *             &lt;/sequence>
     *           &lt;/choice>
     *           &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *             &lt;element ref="{}Account" minOccurs="0"/>
     *           &lt;/sequence>
     *           &lt;element ref="{}Period" minOccurs="0"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *       &lt;attribute name="marketType" type="{}MarketTypeType" />
     *       &lt;attribute name="originCountry" type="{}CountryCodeType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "content"
    })
    public static class SearchCriteria {

        @XmlElementRefs({
                @XmlElementRef(name = "PieceReference", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Account", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "CustomerReference", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "AlternativeConsignmentNumber", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Period", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "ConsignmentNumber", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> content;
        @XmlAttribute(name = "marketType")
        protected MarketTypeType marketType;
        @XmlAttribute(name = "originCountry")
        protected String originCountry;

        /**
         * Gets the rest of the content model.
         * <p>
         * <p>
         * You are getting this "catch-all" property because of the following reason:
         * The field name "Period" is used by two different parts of a schema. See:
         * line 31 of file:/E:/Workspace/Java/xms2/xms-delivery/api/tnt/intl/xsd/tracking_request.xsd
         * line 11 of file:/E:/Workspace/Java/xms2/xms-delivery/api/tnt/intl/xsd/tracking_request.xsd
         * <p>
         * To get rid of this property, apply a property customization to one
         * of both of the following declarations to change their names:
         * Gets the value of the content property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link AccountStructure }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link TimeFrameStructure }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         */
        public List<JAXBElement<?>> getContent() {
            if (content == null) {
                content = new ArrayList<JAXBElement<?>>();
            }
            return this.content;
        }

        /**
         * Gets the value of the marketType property.
         *
         * @return possible object is
         * {@link MarketTypeType }
         */
        public MarketTypeType getMarketType() {
            return marketType;
        }

        /**
         * Sets the value of the marketType property.
         *
         * @param value allowed object is
         *              {@link MarketTypeType }
         */
        public void setMarketType(MarketTypeType value) {
            this.marketType = value;
        }

        /**
         * Gets the value of the originCountry property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOriginCountry() {
            return originCountry;
        }

        /**
         * Sets the value of the originCountry property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOriginCountry(String value) {
            this.originCountry = value;
        }

    }

}
