//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:33:23 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.shipping.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Collection complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Collection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="COLLECTIONADDRESS" type="{}CollectionAddress"/>
 *         &lt;/sequence>
 *         &lt;element name="SHIPDATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PREFCOLLECTTIME" type="{}CollectTime"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="ALTCOLLECTTIME" type="{}CollectTime"/>
 *         &lt;/sequence>
 *         &lt;element name="COLLINSTRUCTIONS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="CONFIRMATIONEMAILADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Collection", propOrder = {
        "collectionaddress",
        "shipdate",
        "prefcollecttime",
        "altcollecttime",
        "collinstructions",
        "confirmationemailaddress"
})
public class Collection {

    @XmlElement(name = "COLLECTIONADDRESS")
    protected CollectionAddress collectionaddress;
    @XmlElement(name = "SHIPDATE", required = true)
    protected String shipdate;
    @XmlElement(name = "PREFCOLLECTTIME", required = true)
    protected CollectTime prefcollecttime;
    @XmlElement(name = "ALTCOLLECTTIME")
    protected CollectTime altcollecttime;
    @XmlElement(name = "COLLINSTRUCTIONS", required = true)
    protected String collinstructions;
    @XmlElement(name = "CONFIRMATIONEMAILADDRESS")
    protected String confirmationemailaddress;

    /**
     * Gets the value of the collectionaddress property.
     *
     * @return possible object is
     * {@link CollectionAddress }
     */
    public CollectionAddress getCOLLECTIONADDRESS() {
        return collectionaddress;
    }

    /**
     * Sets the value of the collectionaddress property.
     *
     * @param value allowed object is
     *              {@link CollectionAddress }
     */
    public void setCOLLECTIONADDRESS(CollectionAddress value) {
        this.collectionaddress = value;
    }

    /**
     * Gets the value of the shipdate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSHIPDATE() {
        return shipdate;
    }

    /**
     * Sets the value of the shipdate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSHIPDATE(String value) {
        this.shipdate = value;
    }

    /**
     * Gets the value of the prefcollecttime property.
     *
     * @return possible object is
     * {@link CollectTime }
     */
    public CollectTime getPREFCOLLECTTIME() {
        return prefcollecttime;
    }

    /**
     * Sets the value of the prefcollecttime property.
     *
     * @param value allowed object is
     *              {@link CollectTime }
     */
    public void setPREFCOLLECTTIME(CollectTime value) {
        this.prefcollecttime = value;
    }

    /**
     * Gets the value of the altcollecttime property.
     *
     * @return possible object is
     * {@link CollectTime }
     */
    public CollectTime getALTCOLLECTTIME() {
        return altcollecttime;
    }

    /**
     * Sets the value of the altcollecttime property.
     *
     * @param value allowed object is
     *              {@link CollectTime }
     */
    public void setALTCOLLECTTIME(CollectTime value) {
        this.altcollecttime = value;
    }

    /**
     * Gets the value of the collinstructions property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCOLLINSTRUCTIONS() {
        return collinstructions;
    }

    /**
     * Sets the value of the collinstructions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCOLLINSTRUCTIONS(String value) {
        this.collinstructions = value;
    }

    /**
     * Gets the value of the confirmationemailaddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCONFIRMATIONEMAILADDRESS() {
        return confirmationemailaddress;
    }

    /**
     * Sets the value of the confirmationemailaddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCONFIRMATIONEMAILADDRESS(String value) {
        this.confirmationemailaddress = value;
    }

}
