//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:33:23 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.shipping.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ConsignmentBatch complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ConsignmentBatch">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="GROUPCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="SENDER" type="{}Sender"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="CONSIGNMENT" type="{}Consignment"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsignmentBatch", propOrder = {
        "groupcode",
        "sender",
        "consignment"
})
public class ConsignmentBatch {

    @XmlElement(name = "GROUPCODE")
    protected String groupcode;
    @XmlElement(name = "SENDER", required = true)
    protected Sender sender;
    @XmlElement(name = "CONSIGNMENT")
    protected List<Consignment> consignment;

    /**
     * Gets the value of the groupcode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGROUPCODE() {
        return groupcode;
    }

    /**
     * Sets the value of the groupcode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGROUPCODE(String value) {
        this.groupcode = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link Sender }
     */
    public Sender getSENDER() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link Sender }
     */
    public void setSENDER(Sender value) {
        this.sender = value;
    }

    /**
     * Gets the value of the consignment property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consignment property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONSIGNMENT().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Consignment }
     */
    public List<Consignment> getCONSIGNMENT() {
        if (consignment == null) {
            consignment = new ArrayList<Consignment>();
        }
        return this.consignment;
    }

}
