//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:33:23 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.shipping.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Details complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Details">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RECEIVER" type="{}Receiver"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="DELIVERY" type="{}Delivery"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="CONNUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="CUSTOMERREF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CONTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PAYMENTIND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ITEMS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TOTALWEIGHT" type="{}DoubleThreeDecimalPlaces"/>
 *         &lt;element name="TOTALVOLUME" type="{}DoubleThreeDecimalPlaces"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="GOODSVALUE" type="{}DoubleThreeDecimalPlaces"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="INSURANCEVALUE" type="{}DoubleThreeDecimalPlaces"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="INSURANCECURRENCY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="OPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DELIVERYINST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="CUSTOMCONTROLIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="HAZARDOUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="UNNUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PACKAGE" type="{}Package"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Details", propOrder = {
        "receiver",
        "delivery",
        "connumber",
        "customerref",
        "contype",
        "paymentind",
        "items",
        "totalweight",
        "totalvolume",
        "currency",
        "goodsvalue",
        "insurancevalue",
        "insurancecurrency",
        "service",
        "option",
        "description",
        "deliveryinst",
        "customcontrolin",
        "hazardous",
        "unnumber",
        "_package"
})
public class Details {

    @XmlElement(name = "RECEIVER", required = true)
    protected Receiver receiver;
    @XmlElement(name = "DELIVERY")
    protected Delivery delivery;
    @XmlElement(name = "CONNUMBER")
    protected String connumber;
    @XmlElement(name = "CUSTOMERREF", required = true)
    protected String customerref;
    @XmlElement(name = "CONTYPE", required = true)
    protected String contype;
    @XmlElement(name = "PAYMENTIND", required = true)
    protected String paymentind;
    @XmlElement(name = "ITEMS", required = true)
    protected BigInteger items;
    @XmlElement(name = "TOTALWEIGHT", required = true)
    protected BigDecimal totalweight;
    @XmlElement(name = "TOTALVOLUME", required = true)
    protected BigDecimal totalvolume;
    @XmlElement(name = "CURRENCY")
    protected String currency;
    @XmlElement(name = "GOODSVALUE")
    protected BigDecimal goodsvalue;
    @XmlElement(name = "INSURANCEVALUE")
    protected BigDecimal insurancevalue;
    @XmlElement(name = "INSURANCECURRENCY")
    protected String insurancecurrency;
    @XmlElement(name = "SERVICE", required = true)
    protected String service;
    @XmlElement(name = "OPTION")
    protected List<String> option;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "DELIVERYINST", required = true)
    protected String deliveryinst;
    @XmlElement(name = "CUSTOMCONTROLIN")
    protected String customcontrolin;
    @XmlElement(name = "HAZARDOUS")
    protected String hazardous;
    @XmlElement(name = "UNNUMBER")
    protected String unnumber;
    @XmlElement(name = "PACKAGE")
    protected List<Package> _package;

    /**
     * Gets the value of the receiver property.
     *
     * @return possible object is
     * {@link Receiver }
     */
    public Receiver getRECEIVER() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     *
     * @param value allowed object is
     *              {@link Receiver }
     */
    public void setRECEIVER(Receiver value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the delivery property.
     *
     * @return possible object is
     * {@link Delivery }
     */
    public Delivery getDELIVERY() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     *
     * @param value allowed object is
     *              {@link Delivery }
     */
    public void setDELIVERY(Delivery value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the connumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCONNUMBER() {
        return connumber;
    }

    /**
     * Sets the value of the connumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCONNUMBER(String value) {
        this.connumber = value;
    }

    /**
     * Gets the value of the customerref property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCUSTOMERREF() {
        return customerref;
    }

    /**
     * Sets the value of the customerref property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCUSTOMERREF(String value) {
        this.customerref = value;
    }

    /**
     * Gets the value of the contype property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCONTYPE() {
        return contype;
    }

    /**
     * Sets the value of the contype property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCONTYPE(String value) {
        this.contype = value;
    }

    /**
     * Gets the value of the paymentind property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPAYMENTIND() {
        return paymentind;
    }

    /**
     * Sets the value of the paymentind property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPAYMENTIND(String value) {
        this.paymentind = value;
    }

    /**
     * Gets the value of the items property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getITEMS() {
        return items;
    }

    /**
     * Sets the value of the items property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setITEMS(BigInteger value) {
        this.items = value;
    }

    /**
     * Gets the value of the totalweight property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTOTALWEIGHT() {
        return totalweight;
    }

    /**
     * Sets the value of the totalweight property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setTOTALWEIGHT(BigDecimal value) {
        this.totalweight = value;
    }

    /**
     * Gets the value of the totalvolume property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getTOTALVOLUME() {
        return totalvolume;
    }

    /**
     * Sets the value of the totalvolume property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setTOTALVOLUME(BigDecimal value) {
        this.totalvolume = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCURRENCY(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the goodsvalue property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getGOODSVALUE() {
        return goodsvalue;
    }

    /**
     * Sets the value of the goodsvalue property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setGOODSVALUE(BigDecimal value) {
        this.goodsvalue = value;
    }

    /**
     * Gets the value of the insurancevalue property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getINSURANCEVALUE() {
        return insurancevalue;
    }

    /**
     * Sets the value of the insurancevalue property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setINSURANCEVALUE(BigDecimal value) {
        this.insurancevalue = value;
    }

    /**
     * Gets the value of the insurancecurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getINSURANCECURRENCY() {
        return insurancecurrency;
    }

    /**
     * Sets the value of the insurancecurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setINSURANCECURRENCY(String value) {
        this.insurancecurrency = value;
    }

    /**
     * Gets the value of the service property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSERVICE() {
        return service;
    }

    /**
     * Sets the value of the service property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSERVICE(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the option property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOPTION().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getOPTION() {
        if (option == null) {
            option = new ArrayList<String>();
        }
        return this.option;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the deliveryinst property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDELIVERYINST() {
        return deliveryinst;
    }

    /**
     * Sets the value of the deliveryinst property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDELIVERYINST(String value) {
        this.deliveryinst = value;
    }

    /**
     * Gets the value of the customcontrolin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCUSTOMCONTROLIN() {
        return customcontrolin;
    }

    /**
     * Sets the value of the customcontrolin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCUSTOMCONTROLIN(String value) {
        this.customcontrolin = value;
    }

    /**
     * Gets the value of the hazardous property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHAZARDOUS() {
        return hazardous;
    }

    /**
     * Sets the value of the hazardous property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHAZARDOUS(String value) {
        this.hazardous = value;
    }

    /**
     * Gets the value of the unnumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUNNUMBER() {
        return unnumber;
    }

    /**
     * Sets the value of the unnumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUNNUMBER(String value) {
        this.unnumber = value;
    }

    /**
     * Gets the value of the package property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPACKAGE().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Package }
     */
    public List<Package> getPACKAGE() {
        if (_package == null) {
            _package = new ArrayList<Package>();
        }
        return this._package;
    }

}
