//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 04:33:23 PM ICT 
//


package com.gms.delivery.tnt.xmlpi.shipping.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.gms.delivery.tnt.xmlpi.shipment.request package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gms.delivery.tnt.xmlpi.shipment.request
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Activity }
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link EShipper }
     */
    public EShipper createESHIPPER() {
        return new EShipper();
    }

    /**
     * Create an instance of {@link Login }
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link ConsignmentBatch }
     */
    public ConsignmentBatch createConsignmentBatch() {
        return new ConsignmentBatch();
    }

    /**
     * Create an instance of {@link Book }
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Details }
     */
    public Details createDetails() {
        return new Details();
    }

    /**
     * Create an instance of {@link CollectTime }
     */
    public CollectTime createCollectTime() {
        return new CollectTime();
    }

    /**
     * Create an instance of {@link Manifest }
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link Sender }
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link EmailTo }
     */
    public EmailTo createEmailTo() {
        return new EmailTo();
    }

    /**
     * Create an instance of {@link Connote }
     */
    public Connote createConnote() {
        return new Connote();
    }

    /**
     * Create an instance of {@link Create }
     */
    public Create createCreate() {
        return new Create();
    }

    /**
     * Create an instance of {@link Package }
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Rate }
     */
    public Rate createRate() {
        return new Rate();
    }

    /**
     * Create an instance of {@link Collection }
     */
    public Collection createCollection() {
        return new Collection();
    }

    /**
     * Create an instance of {@link Delivery }
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link Consignment }
     */
    public Consignment createConsignment() {
        return new Consignment();
    }

    /**
     * Create an instance of {@link Invoice }
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link Print }
     */
    public Print createPrint() {
        return new Print();
    }

    /**
     * Create an instance of {@link Article }
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Ship }
     */
    public Ship createShip() {
        return new Ship();
    }

    /**
     * Create an instance of {@link Required }
     */
    public Required createRequired() {
        return new Required();
    }

    /**
     * Create an instance of {@link CollectionAddress }
     */
    public CollectionAddress createCollectionAddress() {
        return new CollectionAddress();
    }

    /**
     * Create an instance of {@link Receiver }
     */
    public Receiver createReceiver() {
        return new Receiver();
    }

    /**
     * Create an instance of {@link Label }
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Activity.SHOWGROUPCODE }
     */
    public Activity.SHOWGROUPCODE createActivitySHOWGROUPCODE() {
        return new Activity.SHOWGROUPCODE();
    }

}
