//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 03:26:24 PM ICT 
//


package com.gms.delivery.startrack.xmlpi.booking.aaecreateeconnote;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AaEConnoteBinaryResult complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="AaEConnoteBinaryResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ConnoteNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LabelsPDF" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="ManifestPDF" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AaEConnoteBinaryResult", propOrder = {
        "connoteNumber",
        "labelsPDF",
        "manifestPDF"
})
public class AaEConnoteBinaryResult {

    @XmlElementRef(name = "ConnoteNumber", namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", type = JAXBElement.class, required = false)
    protected JAXBElement<String> connoteNumber;
    @XmlElementRef(name = "LabelsPDF", namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", type = JAXBElement.class, required = false)
    protected JAXBElement<byte[]> labelsPDF;
    @XmlElementRef(name = "ManifestPDF", namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", type = JAXBElement.class, required = false)
    protected JAXBElement<byte[]> manifestPDF;

    /**
     * Gets the value of the connoteNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getConnoteNumber() {
        return connoteNumber;
    }

    /**
     * Sets the value of the connoteNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setConnoteNumber(JAXBElement<String> value) {
        this.connoteNumber = value;
    }

    /**
     * Gets the value of the labelsPDF property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    public JAXBElement<byte[]> getLabelsPDF() {
        return labelsPDF;
    }

    /**
     * Sets the value of the labelsPDF property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    public void setLabelsPDF(JAXBElement<byte[]> value) {
        this.labelsPDF = value;
    }

    /**
     * Gets the value of the manifestPDF property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    public JAXBElement<byte[]> getManifestPDF() {
        return manifestPDF;
    }

    /**
     * Sets the value of the manifestPDF property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    public void setManifestPDF(JAXBElement<byte[]> value) {
        this.manifestPDF = value;
    }

}
