//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 03:26:24 PM ICT 
//


package com.gms.delivery.startrack.xmlpi.booking.aaecreateeconnote;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.datacontract.schemas._2004._07.aaecreateeconnote package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AaEConnoteResult_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "AaEConnoteResult");
    private final static QName _AaEConnoteBinaryResult_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "AaEConnoteBinaryResult");
    private final static QName _AaEConnoteZPLResult_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "AaEConnoteZPLResult");
    private final static QName _AaEConnoteZPLResultConnoteNumber_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "ConnoteNumber");
    private final static QName _AaEConnoteZPLResultLabelsZPL_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "LabelsZPL");
    private final static QName _AaEConnoteZPLResultManifestPDF_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "ManifestPDF");
    private final static QName _AaEConnoteBinaryResultLabelsPDF_QNAME = new QName("http://schemas.datacontract.org/2004/07/AaECreateEConnote", "LabelsPDF");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacontract.schemas._2004._07.aaecreateeconnote
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AaEConnoteResult }
     */
    public AaEConnoteResult createAaEConnoteResult() {
        return new AaEConnoteResult();
    }

    /**
     * Create an instance of {@link AaEConnoteBinaryResult }
     */
    public AaEConnoteBinaryResult createAaEConnoteBinaryResult() {
        return new AaEConnoteBinaryResult();
    }

    /**
     * Create an instance of {@link AaEConnoteZPLResult }
     */
    public AaEConnoteZPLResult createAaEConnoteZPLResult() {
        return new AaEConnoteZPLResult();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AaEConnoteResult }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "AaEConnoteResult")
    public JAXBElement<AaEConnoteResult> createAaEConnoteResult(AaEConnoteResult value) {
        return new JAXBElement<AaEConnoteResult>(_AaEConnoteResult_QNAME, AaEConnoteResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AaEConnoteBinaryResult }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "AaEConnoteBinaryResult")
    public JAXBElement<AaEConnoteBinaryResult> createAaEConnoteBinaryResult(AaEConnoteBinaryResult value) {
        return new JAXBElement<AaEConnoteBinaryResult>(_AaEConnoteBinaryResult_QNAME, AaEConnoteBinaryResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AaEConnoteZPLResult }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "AaEConnoteZPLResult")
    public JAXBElement<AaEConnoteZPLResult> createAaEConnoteZPLResult(AaEConnoteZPLResult value) {
        return new JAXBElement<AaEConnoteZPLResult>(_AaEConnoteZPLResult_QNAME, AaEConnoteZPLResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "ConnoteNumber", scope = AaEConnoteZPLResult.class)
    public JAXBElement<String> createAaEConnoteZPLResultConnoteNumber(String value) {
        return new JAXBElement<String>(_AaEConnoteZPLResultConnoteNumber_QNAME, String.class, AaEConnoteZPLResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "LabelsZPL", scope = AaEConnoteZPLResult.class)
    public JAXBElement<byte[]> createAaEConnoteZPLResultLabelsZPL(byte[] value) {
        return new JAXBElement<byte[]>(_AaEConnoteZPLResultLabelsZPL_QNAME, byte[].class, AaEConnoteZPLResult.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "ManifestPDF", scope = AaEConnoteZPLResult.class)
    public JAXBElement<byte[]> createAaEConnoteZPLResultManifestPDF(byte[] value) {
        return new JAXBElement<byte[]>(_AaEConnoteZPLResultManifestPDF_QNAME, byte[].class, AaEConnoteZPLResult.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "ConnoteNumber", scope = AaEConnoteBinaryResult.class)
    public JAXBElement<String> createAaEConnoteBinaryResultConnoteNumber(String value) {
        return new JAXBElement<String>(_AaEConnoteZPLResultConnoteNumber_QNAME, String.class, AaEConnoteBinaryResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "LabelsPDF", scope = AaEConnoteBinaryResult.class)
    public JAXBElement<byte[]> createAaEConnoteBinaryResultLabelsPDF(byte[] value) {
        return new JAXBElement<byte[]>(_AaEConnoteBinaryResultLabelsPDF_QNAME, byte[].class, AaEConnoteBinaryResult.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "ManifestPDF", scope = AaEConnoteBinaryResult.class)
    public JAXBElement<byte[]> createAaEConnoteBinaryResultManifestPDF(byte[] value) {
        return new JAXBElement<byte[]>(_AaEConnoteZPLResultManifestPDF_QNAME, byte[].class, AaEConnoteBinaryResult.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/AaECreateEConnote", name = "ConnoteNumber", scope = AaEConnoteResult.class)
    public JAXBElement<String> createAaEConnoteResultConnoteNumber(String value) {
        return new JAXBElement<String>(_AaEConnoteZPLResultConnoteNumber_QNAME, String.class, AaEConnoteResult.class, value);
    }

}
