//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 10:40:46 AM ICT 
//


package com.gms.delivery.startrack.xmlpi.tracking.request;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{}header"/&gt;
 *         &lt;element name="consignmentId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "consignmentId"
})
@XmlRootElement(name = "getConsignmentDetailRequest")
public class GetConsignmentDetailRequest {

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected String consignmentId;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link Header }
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link Header }
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the consignmentId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConsignmentId() {
        return consignmentId;
    }

    /**
     * Sets the value of the consignmentId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConsignmentId(String value) {
        this.consignmentId = value;
    }

}
