package test.com.gms.xms.integration.startrack;

import com.gms.delivery.startrack.service.StarTrackScheduleService;

public class StarTrackScheduleServiceTest {
    public static void main(String[] args) throws Exception {
        String xmlRequest = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tem=\"http://tempuri.org/\" xmlns:aaec=\"http://schemas.datacontract.org/2004/07/AaECreateBooking\"><soapenv:Header><wsse:Security soapenv:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><wsse:UsernameToken wsu:Id=\"UsernameToken-1\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"><wsse:Username>agl</wsse:Username><wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">nNmx.$7t4Z</wsse:Password><wsse:Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">eWKkxq3KfihkOn1QisM+Rw==</wsse:Nonce><wsu:Created>2011-03-21T01:48:08.609Z</wsu:Created></wsse:UsernameToken></wsse:Security></soapenv:Header><soapenv:Body><tem:CreateBooking><!--Optional: --><tem:composite><!--Optional: --><aaec:CustId>10143119</aaec:CustId><aaec:CustReference>EL0612</aaec:CustReference><aaec:ItemCount>1</aaec:ItemCount><aaec:ItemDescription>Shoes</aaec:ItemDescription><aaec:PickupDate>1/12/2015</aaec:PickupDate><aaec:PickupLatest>17:00</aaec:PickupLatest><aaec:PickupTime>13:30</aaec:PickupTime><aaec:ReceiverAddr1>55 Hawthorn St</aaec:ReceiverAddr1><aaec:ReceiverCity>RAMSGATE BEACH</aaec:ReceiverCity><aaec:ReceiverContactName>n/a</aaec:ReceiverContactName><aaec:ReceiverName>SAMPLE AUSTRALIA PTY LTD</aaec:ReceiverName><aaec:ReceiverPhone>0295830000</aaec:ReceiverPhone><aaec:ReceiverPostCode>2217</aaec:ReceiverPostCode><aaec:SenderAddr1>1239 some street</aaec:SenderAddr1><aaec:SenderAddr2>Level 5</aaec:SenderAddr2><aaec:SenderCity>BANYO</aaec:SenderCity><aaec:SenderContactArea>Reception</aaec:SenderContactArea><aaec:SenderContactName>Michelle</aaec:SenderContactName><aaec:SenderEmailAddress>datotestmail@gmail.com</aaec:SenderEmailAddress><aaec:SenderName>Agl</aaec:SenderName><aaec:SenderPhone>0409434287</aaec:SenderPhone><aaec:SenderPostCode>4014</aaec:SenderPostCode><aaec:ServiceType>PRM</aaec:ServiceType><aaec:ShipInstructions /><aaec:TotalWeight>1</aaec:TotalWeight></tem:composite></tem:CreateBooking></soapenv:Body></soapenv:Envelope>";
        StarTrackScheduleService bookingService = new StarTrackScheduleService();
        String xmlResponse = bookingService.execute(xmlRequest, null);
        System.out.println("Response: " + xmlResponse);
        System.out.println("Error: " + bookingService.getErrorMessage(xmlResponse));
    }
}
