package com.gms.delivery.ups.service.rest.transit.response.transiteTimeResponse;

import java.util.List;

public class TNTSERVICESUMMARY {

	private List<TNTSERVICE> TNTSERVICE;

    private List<TNTGUARANTEEDINDICATOR> TNTGUARANTEEDINDICATOR;

    private List<TNTESTIMATEDARRIVAL> TNTESTIMATEDARRIVAL;

    public void setTNTSERVICE(List<TNTSERVICE> TNTSERVICE){
        this.TNTSERVICE = TNTSERVICE;
    }
    public List<TNTSERVICE> getTNTSERVICE(){
        return this.TNTSERVICE;
    }
    public void setTNTGUARANTEEDINDICATOR(List<TNTGUARANTEEDINDICATOR> TNTGUARANTEEDINDICATOR){
        this.TNTGUARANTEEDINDICATOR = TNTGUARANTEEDINDICATOR;
    }
    public List<TNTGUARANTEEDINDICATOR> getTNTGUARANTEEDINDICATOR(){
        return this.TNTGUARANTEEDINDICATOR;
    }
    public void setTNTESTIMATEDARRIVAL(List<TNTESTIMATEDARRIVAL> TNTESTIMATEDARRIVAL){
        this.TNTESTIMATEDARRIVAL = TNTESTIMATEDARRIVAL;
    }
    public List<TNTESTIMATEDARRIVAL> getTNTESTIMATEDARRIVAL(){
        return this.TNTESTIMATEDARRIVAL;
    }
}
