//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.27 at 02:18:52 PM ICT 
//


package com.gms.delivery.dhl.xmlpi.datatype.pickup.book;

import com.gms.delivery.dhl.xmlpi.datatype.*;
import com.gms.delivery.dhl.xmlpi.datatype.pickup.Pickup;
import com.gms.delivery.dhl.xmlpi.datatype.pickup.Requestor;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Request" type="{http://www.dhl.com/datatypes_global}Request"/&gt;
 *         &lt;element name="RegionCode" type="{http://www.dhl.com/datatypes_global}RegionCode"/&gt;
 *         &lt;element name="Requestor" type="{http://www.dhl.com/pickupdatatypes_global}Requestor"/&gt;
 *         &lt;element name="Place" type="{http://www.dhl.com/pickupdatatypes_global}Place"/&gt;
 *         &lt;element name="Pickup" type="{http://www.dhl.com/pickupdatatypes_global}Pickup"/&gt;
 *         &lt;element name="PickupContact" type="{http://www.dhl.com/pickupdatatypes_global}contact"/&gt;
 *         &lt;element name="ShipmentDetails" type="{http://www.dhl.com/pickupdatatypes_global}ShipmentDetails" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "request",
        "regionCode",
        "requestor",
        "place",
        "pickup",
        "pickupContact",
        "shipmentDetails"
})
@XmlRootElement(name = "BookPURequest")
public class BookPURequest {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "RegionCode", required = true)
    @XmlSchemaType(name = "string")
    protected RegionCode regionCode;
    @XmlElement(name = "Requestor", required = true)
    protected Requestor requestor;
    @XmlElement(name = "Place", required = true)
    protected Place place;
    @XmlElement(name = "Pickup", required = true)
    protected Pickup pickup;
    @XmlElement(name = "PickupContact", required = true)
    protected Contact pickupContact;
    @XmlElement(name = "ShipmentDetails")
    protected List<ShipmentDetails> shipmentDetails;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected BigDecimal schemaVersion;

    /**
     * Gets the value of the request property.
     *
     * @return possible object is
     * {@link Request }
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     *
     * @param value allowed object is
     *              {@link Request }
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the regionCode property.
     *
     * @return possible object is
     * {@link RegionCode }
     */
    public RegionCode getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     *
     * @param value allowed object is
     *              {@link RegionCode }
     */
    public void setRegionCode(RegionCode value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the requestor property.
     *
     * @return possible object is
     * {@link Requestor }
     */
    public Requestor getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     *
     * @param value allowed object is
     *              {@link Requestor }
     */
    public void setRequestor(Requestor value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the place property.
     *
     * @return possible object is
     * {@link Place }
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     *
     * @param value allowed object is
     *              {@link Place }
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the pickup property.
     *
     * @return possible object is
     * {@link Pickup }
     */
    public Pickup getPickup() {
        return pickup;
    }

    /**
     * Sets the value of the pickup property.
     *
     * @param value allowed object is
     *              {@link Pickup }
     */
    public void setPickup(Pickup value) {
        this.pickup = value;
    }

    /**
     * Gets the value of the pickupContact property.
     *
     * @return possible object is
     * {@link Contact }
     */
    public Contact getPickupContact() {
        return pickupContact;
    }

    /**
     * Sets the value of the pickupContact property.
     *
     * @param value allowed object is
     *              {@link Contact }
     */
    public void setPickupContact(Contact value) {
        this.pickupContact = value;
    }

    /**
     * Gets the value of the shipmentDetails property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipmentDetails property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipmentDetails().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentDetails }
     */
    public List<ShipmentDetails> getShipmentDetails() {
        if (shipmentDetails == null) {
            shipmentDetails = new ArrayList<ShipmentDetails>();
        }
        return this.shipmentDetails;
    }

    /**
     * Gets the value of the schemaVersion property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getSchemaVersion() {
        if (schemaVersion == null) {
            return new BigDecimal("1.0");
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setSchemaVersion(BigDecimal value) {
        this.schemaVersion = value;
    }

}
